// <auto-generated />
using System;
using Furniking.DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Furniking.DAL.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230414135509_AddedFakeDatas")]
    partial class AddedFakeDatas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Furniking.DAL.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Tools"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Kids"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Shoes"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Tools & Movies"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Toys"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Grocery, Toys & Sports"
                        });
                });

            modelBuilder.Entity("Furniking.DAL.Entities.Furniture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Furnitures");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Ab voluptas illum facilis voluptatem ullam soluta sit. Id consequatur assumenda voluptatem culpa ea. Eligendi eveniet quia sed aperiam nihil voluptatem aliquam temporibus. Ut et iure.",
                            Name = "Ergonomic Soft Car",
                            Price = 841.980151623315970m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Description = "Omnis eius ducimus. Asperiores impedit est autem quia sit consequatur est tempora ut. Sit corrupti nemo est suscipit sint. Ad magnam rerum et et nulla neque.",
                            Name = "Unbranded Cotton Bike",
                            Price = 279.741756547623250m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 6,
                            Description = "Similique sit minima sunt. Autem ea veniam facilis et amet aliquam. Ut in ut. Autem fuga qui rerum vero iure molestiae eum rerum.",
                            Name = "Tasty Steel Car",
                            Price = 426.994886512878850m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            Description = "Ipsa aut qui suscipit voluptatum ut expedita et. Non cum minus. Quibusdam deserunt et voluptatum labore veritatis delectus molestiae voluptatem.",
                            Name = "Awesome Plastic Hat",
                            Price = 94.6081843558810210m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 5,
                            Description = "Aperiam tenetur doloremque. Est est hic qui. Pariatur et repudiandae. Et numquam occaecati dolores aspernatur. Voluptatibus sapiente fuga et iste voluptatem ut et rerum dolor.",
                            Name = "Unbranded Wooden Computer",
                            Price = 955.112962107483730m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Description = "Eos quos architecto accusamus adipisci harum. Doloribus nobis neque adipisci aut iste. Harum aspernatur illo.",
                            Name = "Practical Cotton Sausages",
                            Price = 43.8007295829899080m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            Description = "Maiores delectus iure necessitatibus animi. Quo ratione sint voluptatem inventore porro aliquid maxime rerum. Rerum reiciendis rem excepturi aut alias ut deleniti.",
                            Name = "Awesome Rubber Towels",
                            Price = 527.63788635323050m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            Description = "Voluptatem illum esse enim porro quae porro placeat. Illum repudiandae nostrum voluptas et et maiores. Omnis explicabo odit dolorem minus. Voluptatum quas hic. Asperiores recusandae molestias soluta.",
                            Name = "Small Concrete Chips",
                            Price = 208.3066207035760m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            Description = "Qui necessitatibus at velit fugiat fuga ut quae consequuntur. Omnis labore eius impedit tenetur. Minus dolor eius. Cumque illo reprehenderit qui sed illum sint.",
                            Name = "Practical Cotton Keyboard",
                            Price = 842.26919647560040m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 3,
                            Description = "Non velit dolore aut consequatur et repellat officiis voluptatum. Error optio quo soluta culpa qui expedita eos. Cumque eius id aperiam facilis. Vitae temporibus aut.",
                            Name = "Tasty Fresh Computer",
                            Price = 419.832838915772140m
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 1,
                            Description = "Sit molestias pariatur ea maxime omnis. Est ratione voluptas inventore aut at et. Delectus in soluta eos quia nesciunt adipisci. Est nesciunt cum a nulla quibusdam. Voluptas nesciunt reiciendis laborum.",
                            Name = "Refined Wooden Pizza",
                            Price = 286.358920472577250m
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 6,
                            Description = "Non sit distinctio incidunt assumenda quae ducimus repellat sapiente animi. Vel et odit dolores aspernatur similique asperiores et placeat voluptatem. Neque laborum perferendis. Totam vel tempora ab eligendi eligendi a.",
                            Name = "Gorgeous Plastic Fish",
                            Price = 20.2007518068948580m
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 6,
                            Description = "Illum et eos sapiente. Dolor qui libero exercitationem voluptas at modi aut non harum. Non quibusdam similique rerum eum eveniet. Sed reprehenderit laudantium sint ipsam.",
                            Name = "Tasty Rubber Salad",
                            Price = 804.916695075078070m
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 3,
                            Description = "Nemo dignissimos quia. Ad fugit sed est laborum. Amet delectus suscipit eos dolorem at ullam. Aut amet quae tempora cumque laboriosam suscipit.",
                            Name = "Handmade Plastic Chicken",
                            Price = 975.965440516640740m
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 5,
                            Description = "Modi pariatur alias. Impedit nesciunt doloremque autem aut. At optio velit voluptas esse voluptates modi esse quia molestiae. Sed in dolorem maxime qui tempore quia ut aut a.",
                            Name = "Rustic Granite Tuna",
                            Price = 762.89931215176150m
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 3,
                            Description = "Sapiente autem occaecati voluptas placeat eaque. Quis id voluptatem. Officia qui harum modi ad sed non consequuntur. Non deleniti sint nobis. Sit voluptatem delectus adipisci dicta voluptatem iusto quia aliquam. Quisquam iure nulla occaecati nostrum.",
                            Name = "Tasty Concrete Pizza",
                            Price = 530.815256551840690m
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 2,
                            Description = "Hic autem dolores autem expedita. Dolor error ea exercitationem eligendi omnis. Possimus incidunt natus voluptatem sit maiores ipsam sunt.",
                            Name = "Unbranded Metal Chips",
                            Price = 552.34276929836740m
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 2,
                            Description = "Sit ducimus et. Eum sapiente nihil in sed. Modi est dolore. Sed impedit necessitatibus. Fuga omnis doloribus provident qui ea laborum et sed hic. Quae praesentium molestiae.",
                            Name = "Intelligent Cotton Computer",
                            Price = 771.283651770562690m
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 1,
                            Description = "Molestiae suscipit laborum rerum optio atque voluptas qui. Quia recusandae maxime aperiam sunt voluptas voluptas eius ratione qui. Cupiditate et quasi iste accusamus ipsam. Alias et est non modi. Numquam et itaque praesentium nisi autem recusandae optio.",
                            Name = "Intelligent Plastic Hat",
                            Price = 762.835535610543550m
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 3,
                            Description = "Consequatur qui est et atque minima laboriosam deserunt facilis. Tenetur quo adipisci tempore ut voluptatem harum vero sapiente itaque. Ea voluptates et sit natus ut. Rerum vitae repudiandae. Non assumenda quam nulla provident blanditiis autem assumenda. Magni nulla praesentium sunt quis molestiae similique perspiciatis eos labore.",
                            Name = "Unbranded Wooden Table",
                            Price = 551.023591152846340m
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 6,
                            Description = "Vero et modi aliquid. Sit qui dolore non eius excepturi omnis quam. Consequuntur id maiores ab iure consectetur et error. Sed nesciunt eum sit tempora et laboriosam consequatur sint. Dolorum quisquam voluptatibus ipsa eos doloremque expedita quo consequatur illum. Rem fuga incidunt possimus iusto voluptatem quis.",
                            Name = "Fantastic Soft Bacon",
                            Price = 231.554631034003960m
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 5,
                            Description = "Voluptas odio a cumque explicabo nihil. Exercitationem corrupti officiis voluptate qui magni libero temporibus. Esse et quam sapiente ut vel repudiandae. Veritatis alias tempora ullam porro possimus et ut itaque. Et officiis unde quo vel aliquam voluptatem omnis et. Sunt veniam non aut sunt nostrum et.",
                            Name = "Unbranded Metal Chair",
                            Price = 156.945839281580350m
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 5,
                            Description = "Nesciunt aut corporis quibusdam beatae sit veritatis animi totam corrupti. Dicta iste porro maxime. Optio sequi totam. Unde et in inventore voluptatem aperiam. Assumenda dolor rerum assumenda sunt sint suscipit. Rem repudiandae eaque quaerat error voluptatum ut unde.",
                            Name = "Awesome Plastic Chips",
                            Price = 594.734779646381980m
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 3,
                            Description = "Dolorem ex numquam quas. Quos neque labore dolorem. Aut alias quaerat eaque animi quo fuga eius ut repudiandae.",
                            Name = "Intelligent Plastic Sausages",
                            Price = 202.544716774159090m
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 1,
                            Description = "Magnam non pariatur quod voluptas rerum. Eum harum aut non et quibusdam voluptatem similique. Ut accusamus ab voluptas omnis et quasi delectus quod exercitationem. Dignissimos consequatur pariatur quo dolore tenetur modi. Non cumque rem ea iure possimus esse. Nostrum dolore expedita rerum praesentium quia consequatur et deleniti.",
                            Name = "Rustic Steel Ball",
                            Price = 22.1144640307966990m
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 5,
                            Description = "Ab sit sunt minus quod. Ipsa nihil ratione. Ad asperiores ut nemo. Velit assumenda et numquam et voluptatibus rem et. Repellendus pariatur et totam. Veniam deserunt repudiandae rem neque minus occaecati corrupti ut.",
                            Name = "Refined Granite Chicken",
                            Price = 435.500216429238280m
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 6,
                            Description = "Pariatur eum magnam reprehenderit. Voluptas qui est illo eum. Aut et dolores eum. Incidunt et quibusdam ut. Qui error exercitationem et.",
                            Name = "Rustic Granite Pizza",
                            Price = 120.748882778932420m
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 6,
                            Description = "Veritatis illo voluptate. Voluptas dolorem nihil provident et consectetur hic qui. Enim dicta et inventore nemo omnis. Rerum et et facere error dolore. Sunt voluptate quia ea voluptatem id. Nobis est ut repudiandae et sed et.",
                            Name = "Intelligent Cotton Chair",
                            Price = 166.94993805634990m
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 1,
                            Description = "Repellat deleniti sed suscipit asperiores deserunt ipsam itaque tempora. Ut quo quia. Molestias architecto et aut autem nostrum architecto et.",
                            Name = "Practical Concrete Car",
                            Price = 412.131309110776630m
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 4,
                            Description = "Rerum quam tenetur quibusdam blanditiis et consectetur ratione. Voluptate dolor explicabo similique a quia sed hic quas. Explicabo rerum voluptatum. Quisquam voluptas qui magni sunt illo sed minima. Exercitationem nostrum eos quas dolores aut autem nulla ut explicabo.",
                            Name = "Ergonomic Soft Pizza",
                            Price = 487.206234467338420m
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 6,
                            Description = "Sit consequuntur amet illum provident expedita nisi numquam assumenda nisi. Vel voluptatem quod quo. Libero nesciunt odio. Quia facilis est quis minus repudiandae.",
                            Name = "Practical Frozen Pizza",
                            Price = 187.070546413854280m
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 2,
                            Description = "Quis porro eos sunt est. Enim ipsam et cumque et odit. Soluta voluptas sit beatae natus sequi asperiores repudiandae a.",
                            Name = "Refined Metal Fish",
                            Price = 672.744758778072190m
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 6,
                            Description = "Hic assumenda sed at odio vel sapiente non ipsa. Et vero iusto qui aut nesciunt occaecati fugit quia. Quo qui alias. Molestiae voluptatem aut dicta. Et vero reiciendis accusantium atque et eligendi. Dolores voluptate ut et repellendus eius dolore quia non voluptas.",
                            Name = "Intelligent Plastic Towels",
                            Price = 394.252947989070490m
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 5,
                            Description = "Nostrum reprehenderit est aut voluptas praesentium quas facere. Et numquam dolorum id et. Delectus qui omnis. Eos a quo voluptas quam ex corrupti error. Voluptatem est omnis iste voluptatibus at repellendus ut omnis voluptatem.",
                            Name = "Fantastic Plastic Chips",
                            Price = 138.723375096937720m
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 6,
                            Description = "Rerum id voluptas est ut ut et. A sapiente aut. Quis dolor assumenda quia necessitatibus eos nisi sunt. Optio fugit deleniti et.",
                            Name = "Intelligent Rubber Tuna",
                            Price = 518.972609083394170m
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 3,
                            Description = "Error quibusdam eius consequatur optio. Repellendus dolor facilis. Molestias omnis facere.",
                            Name = "Gorgeous Wooden Hat",
                            Price = 982.389437783992360m
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 5,
                            Description = "Quibusdam quidem sunt dolorum asperiores labore ducimus ut debitis amet. Iusto quod nam et corrupti. Aliquam ea libero et est reprehenderit rem sapiente id corporis. Molestiae aliquid tenetur.",
                            Name = "Tasty Plastic Towels",
                            Price = 366.388310126541880m
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 5,
                            Description = "Veniam architecto dolore quidem sit soluta cupiditate. Fuga minima omnis est. Corrupti dolorem alias voluptas amet optio. Voluptatem commodi impedit autem. Reiciendis exercitationem accusantium aut architecto quia tempore. Beatae necessitatibus distinctio dignissimos soluta tenetur quas.",
                            Name = "Fantastic Rubber Mouse",
                            Price = 379.129664809096840m
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 6,
                            Description = "Quia et cumque ea minus modi. Repellat non consequatur. Esse reprehenderit consequatur accusantium neque velit. Est eos autem quo aut tenetur beatae.",
                            Name = "Small Fresh Bike",
                            Price = 125.060475323443870m
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 3,
                            Description = "Non culpa aut est dolor rerum et. Nobis repudiandae suscipit illo impedit. Quisquam voluptate qui quia autem autem enim pariatur debitis deserunt.",
                            Name = "Practical Wooden Computer",
                            Price = 185.669052234109390m
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 4,
                            Description = "Blanditiis ipsam perspiciatis eveniet modi impedit facilis et fugiat officia. Fugit eos facilis doloribus ut suscipit sed ullam tempora. Sed vitae et accusantium praesentium cum aliquam consequatur reiciendis. Est quisquam aut in. Autem ut quaerat voluptate quod quisquam rerum aut ut voluptatibus.",
                            Name = "Tasty Frozen Fish",
                            Price = 100.6104922362324190m
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 2,
                            Description = "In vel quia soluta sequi. Porro id et labore saepe sapiente est. Et adipisci exercitationem quae porro eius temporibus magnam. Unde soluta aperiam ab omnis magnam error enim quia. Quasi dignissimos nisi necessitatibus tenetur harum. Aut voluptas aliquid aut numquam voluptas.",
                            Name = "Intelligent Steel Towels",
                            Price = 582.53742730719370m
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 2,
                            Description = "Consequatur maxime qui facere debitis ex sunt et impedit. Adipisci ea rerum reprehenderit ut. Tempora cupiditate quia sunt sint facilis. A dolore in necessitatibus non eveniet eos aliquid.",
                            Name = "Refined Plastic Chips",
                            Price = 417.034737420943060m
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 5,
                            Description = "Quos magnam sunt. Aliquid vero rerum quaerat sit earum a non voluptatem. Sed ea corrupti beatae facere quasi sint et iure.",
                            Name = "Practical Cotton Soap",
                            Price = 659.83248812370790m
                        },
                        new
                        {
                            Id = 45,
                            CategoryId = 4,
                            Description = "Harum iste qui perspiciatis. Illum dolore quia. Facilis natus omnis voluptatem corporis minima. Voluptatem temporibus quia aperiam est nam. Ut itaque nemo ut voluptatum enim praesentium.",
                            Name = "Incredible Steel Table",
                            Price = 507.895623169034860m
                        },
                        new
                        {
                            Id = 46,
                            CategoryId = 4,
                            Description = "Occaecati reprehenderit est. Dolor quia dolor aliquam provident odit. Vel eos necessitatibus doloremque doloremque labore doloribus corporis ea autem. Ratione dolor sit quo. Qui dolor magnam ratione.",
                            Name = "Sleek Steel Computer",
                            Price = 530.673669560844910m
                        },
                        new
                        {
                            Id = 47,
                            CategoryId = 6,
                            Description = "Esse doloremque cumque enim illum maiores animi. At aperiam similique ea provident labore dicta ipsam provident. Dolorem odit ratione qui quia iusto numquam aliquid maxime fugit. Atque ut esse ut earum officiis quidem placeat repudiandae.",
                            Name = "Licensed Soft Fish",
                            Price = 756.285266428003720m
                        },
                        new
                        {
                            Id = 48,
                            CategoryId = 2,
                            Description = "Omnis voluptate et iusto sed saepe similique corporis magni. Totam expedita facilis nulla quae atque numquam. Sunt et doloribus odit ut optio earum voluptas qui. Id nihil in. Nisi nisi animi rerum non et consectetur et quaerat. Est voluptatem velit aspernatur rerum.",
                            Name = "Sleek Rubber Cheese",
                            Price = 492.602169388753810m
                        },
                        new
                        {
                            Id = 49,
                            CategoryId = 6,
                            Description = "Eius sit architecto. Odio dolores nihil quia ab. Ex qui aperiam soluta iusto. Cumque dicta quo atque non ut.",
                            Name = "Awesome Cotton Cheese",
                            Price = 687.402001860649120m
                        },
                        new
                        {
                            Id = 50,
                            CategoryId = 1,
                            Description = "Ab non temporibus sit nihil dolore sed. Recusandae aliquam ullam vel architecto maxime soluta quo ut officia. Iure quam nihil facere ipsam. Quod incidunt corporis reiciendis qui exercitationem suscipit at hic. Ea quo est quis necessitatibus quo aut cum.",
                            Name = "Handmade Rubber Bacon",
                            Price = 756.776492639713360m
                        });
                });

            modelBuilder.Entity("Furniking.DAL.Entities.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FurnitureId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FurnitureId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("Furniking.DAL.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int>("FurnitureId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FurnitureId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Furniking.DAL.Entities.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Evaluation")
                        .HasColumnType("int");

                    b.Property<int>("FurnitureId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FurnitureId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comment = "Veniam omnis sit ut dolorum aut voluptas. Consequatur officia rem sit odit quis veritatis officia incidunt. Ut labore enim inventore voluptatem id occaecati quo. Itaque praesentium aut quibusdam vel sed dolorum expedita numquam aut.",
                            DateTime = new DateTime(2023, 4, 14, 13, 55, 8, 881, DateTimeKind.Utc).AddTicks(6914),
                            Evaluation = 11,
                            FurnitureId = 27,
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            Comment = "Quia quas eius provident. Sint magni dolor. Aut rerum debitis.",
                            DateTime = new DateTime(2023, 4, 14, 13, 55, 8, 881, DateTimeKind.Utc).AddTicks(7832),
                            Evaluation = 9,
                            FurnitureId = 10,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            Comment = "Quia iste quia optio ea ipsum qui nisi nihil. Nisi veritatis expedita assumenda explicabo. Ut soluta quis qui debitis odit cumque expedita quibusdam reiciendis. Omnis deserunt autem ducimus. Corporis voluptas blanditiis autem quo dolores corrupti. Repellat optio aliquid dolor voluptate sunt omnis non sed repudiandae.",
                            DateTime = new DateTime(2023, 4, 14, 13, 55, 8, 881, DateTimeKind.Utc).AddTicks(8032),
                            Evaluation = 10,
                            FurnitureId = 18,
                            UserId = 2
                        },
                        new
                        {
                            Id = 4,
                            Comment = "Quam accusamus voluptas reprehenderit ut ab natus quasi odio sit. Et quibusdam in consequatur culpa qui. Voluptates est ut rerum consequuntur ex. Non quo recusandae ut nihil cupiditate nemo excepturi. Ratione cupiditate pariatur facilis odit quaerat.",
                            DateTime = new DateTime(2023, 4, 14, 13, 55, 8, 881, DateTimeKind.Utc).AddTicks(8182),
                            Evaluation = 6,
                            FurnitureId = 36,
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            Comment = "Exercitationem laborum deserunt non inventore sint error porro corrupti fugit. Sit sint ipsa. Perspiciatis consequuntur consequuntur quidem sed nam voluptatem blanditiis sint a. Esse commodi exercitationem nam omnis. Earum et ullam.",
                            DateTime = new DateTime(2023, 4, 14, 13, 55, 8, 881, DateTimeKind.Utc).AddTicks(8322),
                            Evaluation = 8,
                            FurnitureId = 6,
                            UserId = 2
                        },
                        new
                        {
                            Id = 6,
                            Comment = "Fugit odit qui non esse cum praesentium optio quia possimus. Aut laboriosam doloribus et in magnam. Aut beatae voluptas. Totam dicta accusantium rerum et consequatur voluptatem. Labore illum doloremque.",
                            DateTime = new DateTime(2023, 4, 14, 13, 55, 8, 881, DateTimeKind.Utc).AddTicks(8465),
                            Evaluation = 8,
                            FurnitureId = 27,
                            UserId = 3
                        },
                        new
                        {
                            Id = 7,
                            Comment = "Error sint quia ullam consequatur repellendus ipsum. Dolorum dolores eum. Sunt laborum quo id accusantium.",
                            DateTime = new DateTime(2023, 4, 14, 13, 55, 8, 881, DateTimeKind.Utc).AddTicks(8573),
                            Evaluation = 10,
                            FurnitureId = 10,
                            UserId = 2
                        },
                        new
                        {
                            Id = 8,
                            Comment = "Sed est quaerat id dolores delectus ipsum qui id praesentium. Ab in optio fugit molestiae suscipit deleniti iusto minima. Rerum molestiae omnis magni. Iusto magnam et. Voluptates odit hic in.",
                            DateTime = new DateTime(2023, 4, 14, 13, 55, 8, 881, DateTimeKind.Utc).AddTicks(8695),
                            Evaluation = 5,
                            FurnitureId = 9,
                            UserId = 1
                        },
                        new
                        {
                            Id = 9,
                            Comment = "Ipsa explicabo unde est distinctio consequuntur voluptas. Culpa quisquam id quasi nihil omnis voluptatem. A velit est voluptatem quia voluptatem. Natus qui exercitationem mollitia fugiat fuga atque est fugit aut.",
                            DateTime = new DateTime(2023, 4, 14, 13, 55, 8, 881, DateTimeKind.Utc).AddTicks(8812),
                            Evaluation = 10,
                            FurnitureId = 18,
                            UserId = 3
                        },
                        new
                        {
                            Id = 10,
                            Comment = "Et eos ut consequuntur. Quasi molestias velit. Vitae omnis id excepturi.",
                            DateTime = new DateTime(2023, 4, 14, 13, 55, 8, 881, DateTimeKind.Utc).AddTicks(8871),
                            Evaluation = 10,
                            FurnitureId = 16,
                            UserId = 3
                        },
                        new
                        {
                            Id = 11,
                            Comment = "Officia tempora vel. Porro sunt in. Dolor voluptatem doloremque sed et dolorem. Quia laudantium consequatur voluptatem deserunt fugiat. Nihil et culpa architecto praesentium totam enim qui omnis beatae.",
                            DateTime = new DateTime(2023, 4, 14, 13, 55, 8, 881, DateTimeKind.Utc).AddTicks(8990),
                            Evaluation = 3,
                            FurnitureId = 8,
                            UserId = 2
                        },
                        new
                        {
                            Id = 12,
                            Comment = "Eos magnam aut rerum dicta. Esse magnam quod veritatis deserunt numquam at rerum dolorem provident. Aut omnis reprehenderit molestiae et dignissimos architecto ut vel. Ut id natus eos molestiae nemo sed rerum eaque maiores. Hic occaecati dolore enim perspiciatis aut.",
                            DateTime = new DateTime(2023, 4, 14, 13, 55, 8, 881, DateTimeKind.Utc).AddTicks(9136),
                            Evaluation = 5,
                            FurnitureId = 32,
                            UserId = 2
                        },
                        new
                        {
                            Id = 13,
                            Comment = "Soluta consequuntur esse alias culpa ut ipsam. Qui eligendi maiores. Ex tenetur voluptatibus porro similique dolorem et. Autem ut iure. Neque sed harum voluptatem voluptas qui repellendus officia.",
                            DateTime = new DateTime(2023, 4, 14, 13, 55, 8, 881, DateTimeKind.Utc).AddTicks(9245),
                            Evaluation = 8,
                            FurnitureId = 44,
                            UserId = 3
                        },
                        new
                        {
                            Id = 14,
                            Comment = "Recusandae pariatur cupiditate cum voluptatum autem. Quis sequi quas quae incidunt ipsum quidem eos dolore odio. In ad cumque ut sint voluptatem corrupti. Ab sint in quis vero. Vel illum non facere quasi deleniti. Veniam reprehenderit ea velit quae corrupti.",
                            DateTime = new DateTime(2023, 4, 14, 13, 55, 8, 881, DateTimeKind.Utc).AddTicks(9398),
                            Evaluation = 6,
                            FurnitureId = 8,
                            UserId = 2
                        },
                        new
                        {
                            Id = 15,
                            Comment = "Iste eaque id quisquam non distinctio. Aliquid architecto asperiores ut enim qui consequatur eos. Facere rem omnis eaque. Sunt possimus quo. Reiciendis cumque tempore repudiandae natus ea ut.",
                            DateTime = new DateTime(2023, 4, 14, 13, 55, 8, 881, DateTimeKind.Utc).AddTicks(9514),
                            Evaluation = 3,
                            FurnitureId = 19,
                            UserId = 1
                        },
                        new
                        {
                            Id = 16,
                            Comment = "Aspernatur modi ut corrupti et quae minima. Sed deleniti placeat qui. Dicta aliquid rerum et repudiandae alias aspernatur quam ea beatae. Dolorum voluptas est delectus quae quasi ea quis. Maiores sint est consequuntur sit optio enim incidunt. Impedit neque nihil omnis.",
                            DateTime = new DateTime(2023, 4, 14, 13, 55, 8, 881, DateTimeKind.Utc).AddTicks(9672),
                            Evaluation = 3,
                            FurnitureId = 8,
                            UserId = 3
                        },
                        new
                        {
                            Id = 17,
                            Comment = "Iste numquam non molestias sit dolor maxime aperiam libero. Voluptatem cupiditate exercitationem et perferendis dolores quia aperiam. Facilis officiis veritatis maxime magni eos voluptates fugiat alias. Veniam dolorem rerum qui. Vel esse quos.",
                            DateTime = new DateTime(2023, 4, 14, 13, 55, 8, 881, DateTimeKind.Utc).AddTicks(9800),
                            Evaluation = 10,
                            FurnitureId = 9,
                            UserId = 2
                        },
                        new
                        {
                            Id = 18,
                            Comment = "Dolorem autem incidunt quia. Porro voluptas odio nemo aut at aut dolor. Et sunt officiis. Et debitis nihil iure dolores esse aut ex.",
                            DateTime = new DateTime(2023, 4, 14, 13, 55, 8, 881, DateTimeKind.Utc).AddTicks(9898),
                            Evaluation = 6,
                            FurnitureId = 5,
                            UserId = 3
                        },
                        new
                        {
                            Id = 19,
                            Comment = "Minima consectetur asperiores eveniet mollitia ad. Rerum quia expedita quaerat ipsa beatae ut ut non aut. Delectus et non a enim et. Minus quasi vero ut voluptas voluptates accusamus ad recusandae omnis.",
                            DateTime = new DateTime(2023, 4, 14, 13, 55, 8, 882, DateTimeKind.Utc).AddTicks(11),
                            Evaluation = 9,
                            FurnitureId = 36,
                            UserId = 1
                        },
                        new
                        {
                            Id = 20,
                            Comment = "Nesciunt aut repudiandae maiores. Voluptas minus nulla deserunt voluptatem quos iusto voluptates sint. Dolorem aut explicabo sed qui. Voluptas incidunt magni est quis beatae tempore eum sed. Velit omnis quia tempora ipsum omnis ipsum.",
                            DateTime = new DateTime(2023, 4, 14, 13, 55, 8, 882, DateTimeKind.Utc).AddTicks(139),
                            Evaluation = 6,
                            FurnitureId = 3,
                            UserId = 1
                        },
                        new
                        {
                            Id = 21,
                            Comment = "Non temporibus mollitia aspernatur in. Deleniti occaecati dolor in et dolorem nesciunt. Et aut a minus.",
                            DateTime = new DateTime(2023, 4, 14, 13, 55, 8, 882, DateTimeKind.Utc).AddTicks(218),
                            Evaluation = 2,
                            FurnitureId = 33,
                            UserId = 1
                        },
                        new
                        {
                            Id = 22,
                            Comment = "Vel temporibus aut mollitia ipsa. Quia et iusto odio ad. Praesentium voluptate sequi rerum. Aut dignissimos dolores error id repudiandae in rem ab blanditiis. A ratione voluptas excepturi adipisci.",
                            DateTime = new DateTime(2023, 4, 14, 13, 55, 8, 882, DateTimeKind.Utc).AddTicks(337),
                            Evaluation = 5,
                            FurnitureId = 47,
                            UserId = 2
                        },
                        new
                        {
                            Id = 23,
                            Comment = "Labore laboriosam suscipit nihil. Aut quasi eos esse porro. Sed at eius sunt tempora impedit consequatur quia mollitia et. Nostrum quidem quia voluptatum. Ipsa atque cumque cumque facere molestias magnam.",
                            DateTime = new DateTime(2023, 4, 14, 13, 55, 8, 882, DateTimeKind.Utc).AddTicks(456),
                            Evaluation = 2,
                            FurnitureId = 50,
                            UserId = 1
                        },
                        new
                        {
                            Id = 24,
                            Comment = "Sit sequi magni est et quae accusamus. In exercitationem quia minima molestiae quo eos. Explicabo aliquid velit.",
                            DateTime = new DateTime(2023, 4, 14, 13, 55, 8, 882, DateTimeKind.Utc).AddTicks(528),
                            Evaluation = 2,
                            FurnitureId = 21,
                            UserId = 1
                        },
                        new
                        {
                            Id = 25,
                            Comment = "Alias iste dolor ut. Et dolor nostrum iste aspernatur amet ut minus et nesciunt. Dolorem et beatae repudiandae. Neque ipsam hic ut.",
                            DateTime = new DateTime(2023, 4, 14, 13, 55, 8, 882, DateTimeKind.Utc).AddTicks(626),
                            Evaluation = 2,
                            FurnitureId = 50,
                            UserId = 1
                        },
                        new
                        {
                            Id = 26,
                            Comment = "Eum nemo accusantium atque rerum expedita voluptatibus vitae veritatis occaecati. Eveniet consectetur id porro officia atque eos. Voluptate harum porro fuga totam velit corrupti iste molestiae et. Quos placeat omnis debitis excepturi aut quo eos. Vel officiis corporis deserunt et. Tenetur quibusdam fugiat in libero enim modi assumenda quas.",
                            DateTime = new DateTime(2023, 4, 14, 13, 55, 8, 882, DateTimeKind.Utc).AddTicks(789),
                            Evaluation = 7,
                            FurnitureId = 43,
                            UserId = 3
                        },
                        new
                        {
                            Id = 27,
                            Comment = "Iusto dicta harum qui quis labore et non reiciendis ullam. Ullam est eveniet ipsum et laudantium vero voluptatem. Corrupti debitis commodi. Molestiae voluptatem totam voluptatibus repellat facere.",
                            DateTime = new DateTime(2023, 4, 14, 13, 55, 8, 882, DateTimeKind.Utc).AddTicks(898),
                            Evaluation = 5,
                            FurnitureId = 47,
                            UserId = 2
                        },
                        new
                        {
                            Id = 28,
                            Comment = "Officia ut rerum sunt dolorem ut. Enim libero magni sit voluptas ex cumque nulla expedita non. Distinctio voluptate est. Est tempora similique aut et odit.",
                            DateTime = new DateTime(2023, 4, 14, 13, 55, 8, 882, DateTimeKind.Utc).AddTicks(998),
                            Evaluation = 5,
                            FurnitureId = 28,
                            UserId = 2
                        },
                        new
                        {
                            Id = 29,
                            Comment = "Aut delectus voluptate quae ea. Itaque quaerat quia ipsa suscipit. Sapiente qui eos vel dolorum quia quia doloribus ipsam dicta. Iure rerum velit aut molestiae. Sint et voluptatem.",
                            DateTime = new DateTime(2023, 4, 14, 13, 55, 8, 882, DateTimeKind.Utc).AddTicks(1107),
                            Evaluation = 5,
                            FurnitureId = 5,
                            UserId = 3
                        },
                        new
                        {
                            Id = 30,
                            Comment = "Sunt sed laboriosam minus quasi. Atque dicta omnis omnis et eveniet rerum in eius quos. Rerum dolorem officia. Fuga facere porro modi eos dolore odio.",
                            DateTime = new DateTime(2023, 4, 14, 13, 55, 8, 882, DateTimeKind.Utc).AddTicks(1262),
                            Evaluation = 6,
                            FurnitureId = 12,
                            UserId = 2
                        },
                        new
                        {
                            Id = 31,
                            Comment = "Nobis eos cupiditate praesentium laborum perspiciatis nostrum sint. Nesciunt est et sed vitae mollitia qui nulla dolor est. Libero animi est itaque corporis est impedit ratione et fuga. Quia quia commodi sed iusto est ipsum. Alias occaecati facilis non qui voluptatum et illum aliquid.",
                            DateTime = new DateTime(2023, 4, 14, 13, 55, 8, 882, DateTimeKind.Utc).AddTicks(1424),
                            Evaluation = 3,
                            FurnitureId = 42,
                            UserId = 3
                        },
                        new
                        {
                            Id = 32,
                            Comment = "Ea error officiis est dolorem repellendus hic officiis. Quos voluptatem consequatur aperiam consequatur possimus. Et eius quia repellendus aut et mollitia et. Soluta velit repudiandae expedita suscipit qui.",
                            DateTime = new DateTime(2023, 4, 14, 13, 55, 8, 882, DateTimeKind.Utc).AddTicks(1535),
                            Evaluation = 3,
                            FurnitureId = 1,
                            UserId = 3
                        },
                        new
                        {
                            Id = 33,
                            Comment = "Ad accusamus nobis nesciunt quidem aut rerum. Iste et unde esse voluptates optio blanditiis. Ex saepe maxime consequuntur architecto. Harum accusantium dolore eos assumenda.",
                            DateTime = new DateTime(2023, 4, 14, 13, 55, 8, 882, DateTimeKind.Utc).AddTicks(1632),
                            Evaluation = 3,
                            FurnitureId = 48,
                            UserId = 2
                        },
                        new
                        {
                            Id = 34,
                            Comment = "Id dignissimos doloribus. Vel aut voluptatem. Est et nulla. Esse quod velit nobis placeat odio unde laboriosam voluptas. Facilis ad vel quis in aliquid et labore.",
                            DateTime = new DateTime(2023, 4, 14, 13, 55, 8, 882, DateTimeKind.Utc).AddTicks(1736),
                            Evaluation = 7,
                            FurnitureId = 13,
                            UserId = 1
                        },
                        new
                        {
                            Id = 35,
                            Comment = "Commodi aliquam necessitatibus fugiat facilis accusantium distinctio accusantium occaecati. Libero qui aspernatur ex illo aperiam doloribus. Ut nihil quia et qui ducimus. Excepturi dolorum suscipit minima quam.",
                            DateTime = new DateTime(2023, 4, 14, 13, 55, 8, 882, DateTimeKind.Utc).AddTicks(1841),
                            Evaluation = 3,
                            FurnitureId = 13,
                            UserId = 3
                        },
                        new
                        {
                            Id = 36,
                            Comment = "Ut repellat tempora velit a suscipit rem debitis. Reiciendis voluptatem explicabo odio est quia. Modi nulla qui.",
                            DateTime = new DateTime(2023, 4, 14, 13, 55, 8, 882, DateTimeKind.Utc).AddTicks(1911),
                            Evaluation = 1,
                            FurnitureId = 44,
                            UserId = 2
                        },
                        new
                        {
                            Id = 37,
                            Comment = "Distinctio sunt et facere labore. Odit qui fugit et necessitatibus qui atque quisquam itaque rerum. Voluptatum aspernatur id deserunt itaque quaerat. Et totam mollitia consequuntur accusamus sit. Omnis deserunt temporibus et aliquam ut.",
                            DateTime = new DateTime(2023, 4, 14, 13, 55, 8, 882, DateTimeKind.Utc).AddTicks(2036),
                            Evaluation = 7,
                            FurnitureId = 7,
                            UserId = 1
                        },
                        new
                        {
                            Id = 38,
                            Comment = "Earum officiis libero. Numquam voluptas sunt voluptatem. Totam vitae quae.",
                            DateTime = new DateTime(2023, 4, 14, 13, 55, 8, 882, DateTimeKind.Utc).AddTicks(2089),
                            Evaluation = 9,
                            FurnitureId = 43,
                            UserId = 3
                        },
                        new
                        {
                            Id = 39,
                            Comment = "Explicabo numquam quos sint dolorum. Autem voluptates eveniet voluptatum placeat. Aut odit provident enim soluta. Iure sunt voluptatem necessitatibus a pariatur sunt repellat sed. Ut quidem esse fugit doloribus repudiandae consequatur possimus.",
                            DateTime = new DateTime(2023, 4, 14, 13, 55, 8, 882, DateTimeKind.Utc).AddTicks(2209),
                            Evaluation = 11,
                            FurnitureId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 40,
                            Comment = "Nobis sequi omnis asperiores modi. Quae nisi voluptatem dolores quia voluptates. Nam vero eum. Omnis dolores corrupti vero aspernatur qui et quia.",
                            DateTime = new DateTime(2023, 4, 14, 13, 55, 8, 882, DateTimeKind.Utc).AddTicks(2296),
                            Evaluation = 2,
                            FurnitureId = 19,
                            UserId = 3
                        },
                        new
                        {
                            Id = 41,
                            Comment = "Adipisci tempora quaerat voluptas id impedit ducimus sit. Ad sapiente atque omnis eveniet. Facere possimus magnam adipisci perferendis.",
                            DateTime = new DateTime(2023, 4, 14, 13, 55, 8, 882, DateTimeKind.Utc).AddTicks(2374),
                            Evaluation = 10,
                            FurnitureId = 23,
                            UserId = 1
                        },
                        new
                        {
                            Id = 42,
                            Comment = "Molestiae non nisi corporis consectetur et rem quasi. Voluptas omnis sequi tempora. Officia harum architecto non accusantium sint fugiat ut eligendi. Delectus laborum ut velit quos corporis sed consequatur commodi aut. Eum et ducimus voluptas magni ea eaque voluptas sunt non. Accusantium occaecati facilis sunt eum nam delectus.",
                            DateTime = new DateTime(2023, 4, 14, 13, 55, 8, 882, DateTimeKind.Utc).AddTicks(2541),
                            Evaluation = 5,
                            FurnitureId = 48,
                            UserId = 2
                        },
                        new
                        {
                            Id = 43,
                            Comment = "Hic omnis debitis suscipit quisquam nihil dolores autem. Recusandae cupiditate omnis. Adipisci cum sequi veniam quidem minima perferendis maxime labore dignissimos. Aut earum quia. Rerum accusamus et veritatis corrupti atque excepturi perferendis. Vel quod rerum quidem eaque et ducimus ut eligendi.",
                            DateTime = new DateTime(2023, 4, 14, 13, 55, 8, 882, DateTimeKind.Utc).AddTicks(2692),
                            Evaluation = 5,
                            FurnitureId = 16,
                            UserId = 2
                        },
                        new
                        {
                            Id = 44,
                            Comment = "Rerum culpa modi eveniet ipsum. Aut sed et inventore ea officiis ut quam hic ullam. Facere itaque qui at ex omnis laborum suscipit expedita quasi. Accusamus ipsam alias corrupti at eum.",
                            DateTime = new DateTime(2023, 4, 14, 13, 55, 8, 882, DateTimeKind.Utc).AddTicks(2803),
                            Evaluation = 4,
                            FurnitureId = 12,
                            UserId = 1
                        },
                        new
                        {
                            Id = 45,
                            Comment = "Non est dolor necessitatibus consequatur nihil perspiciatis. Facere velit harum qui maxime autem distinctio laudantium. Est blanditiis sunt perspiciatis provident. Officiis quo quis itaque officia. Aut ad error excepturi eius iste. Quod ab dolorem quidem ipsam.",
                            DateTime = new DateTime(2023, 4, 14, 13, 55, 8, 882, DateTimeKind.Utc).AddTicks(2941),
                            Evaluation = 10,
                            FurnitureId = 4,
                            UserId = 2
                        },
                        new
                        {
                            Id = 46,
                            Comment = "Recusandae quo nisi dolorem sint. Non nihil voluptatem consectetur sed et. Ut veritatis et sit nihil saepe occaecati qui quos quae. Quia harum debitis. Deserunt repellendus a quaerat dolor.",
                            DateTime = new DateTime(2023, 4, 14, 13, 55, 8, 882, DateTimeKind.Utc).AddTicks(3058),
                            Evaluation = 11,
                            FurnitureId = 36,
                            UserId = 1
                        },
                        new
                        {
                            Id = 47,
                            Comment = "Quo et quod. Quam dolorem aliquid facere delectus ut magnam expedita quos. Deleniti aliquid consequatur et unde repellendus enim a. Tempora accusamus dolore ducimus. Unde sit dolorum quae dolorem qui magnam voluptatem.",
                            DateTime = new DateTime(2023, 4, 14, 13, 55, 8, 882, DateTimeKind.Utc).AddTicks(3175),
                            Evaluation = 9,
                            FurnitureId = 22,
                            UserId = 1
                        },
                        new
                        {
                            Id = 48,
                            Comment = "Accusantium ratione doloremque cumque. Similique amet aut distinctio veritatis itaque fuga magnam. Non similique non. Adipisci non at vitae voluptatibus magni culpa voluptas incidunt sequi. Ex qui qui architecto ducimus qui omnis nihil. Est occaecati accusamus at corporis beatae quae architecto.",
                            DateTime = new DateTime(2023, 4, 14, 13, 55, 8, 882, DateTimeKind.Utc).AddTicks(3326),
                            Evaluation = 11,
                            FurnitureId = 20,
                            UserId = 1
                        },
                        new
                        {
                            Id = 49,
                            Comment = "Eum possimus maxime laboriosam accusamus ut voluptatibus consectetur pariatur sunt. Beatae qui aliquid et est maxime labore ex. Dolores doloremque pariatur nemo rem doloremque ipsum sint. Cumque non ut qui officia aspernatur ipsam cum omnis accusantium. Rerum magni accusantium voluptas qui.",
                            DateTime = new DateTime(2023, 4, 14, 13, 55, 8, 882, DateTimeKind.Utc).AddTicks(3477),
                            Evaluation = 5,
                            FurnitureId = 24,
                            UserId = 3
                        },
                        new
                        {
                            Id = 50,
                            Comment = "Deleniti nulla perferendis odio qui aut qui ut. Rerum natus voluptatibus commodi est sed quasi beatae quasi. Impedit corporis ullam reiciendis. Qui quo beatae et qui optio voluptate dolor. Voluptate consequatur quos.",
                            DateTime = new DateTime(2023, 4, 14, 13, 55, 8, 882, DateTimeKind.Utc).AddTicks(3600),
                            Evaluation = 11,
                            FurnitureId = 2,
                            UserId = 2
                        },
                        new
                        {
                            Id = 51,
                            Comment = "Fuga ut atque accusamus. Natus facere esse iure et nostrum et ducimus sunt. Officia nam aut quia ullam. Harum voluptatem nostrum.",
                            DateTime = new DateTime(2023, 4, 14, 13, 55, 8, 882, DateTimeKind.Utc).AddTicks(3685),
                            Evaluation = 4,
                            FurnitureId = 15,
                            UserId = 1
                        },
                        new
                        {
                            Id = 52,
                            Comment = "Perspiciatis repellat asperiores deleniti iste quasi. Et repellendus minima quia quia inventore qui voluptatem quibusdam rerum. Modi ut architecto repudiandae debitis dolor.",
                            DateTime = new DateTime(2023, 4, 14, 13, 55, 8, 882, DateTimeKind.Utc).AddTicks(3774),
                            Evaluation = 9,
                            FurnitureId = 23,
                            UserId = 1
                        },
                        new
                        {
                            Id = 53,
                            Comment = "Commodi quis ipsum alias voluptas modi. Voluptas rerum facilis odit praesentium. Voluptas nam et. Labore velit neque autem. Et nesciunt doloremque. Sapiente quas quam quia voluptate.",
                            DateTime = new DateTime(2023, 4, 14, 13, 55, 8, 882, DateTimeKind.Utc).AddTicks(3880),
                            Evaluation = 2,
                            FurnitureId = 16,
                            UserId = 1
                        },
                        new
                        {
                            Id = 54,
                            Comment = "Ullam eveniet eveniet doloremque. Assumenda perspiciatis adipisci sed voluptatem at sit. Quia provident consequatur reprehenderit quo dolor rerum non voluptatem. Quae voluptatem est qui.",
                            DateTime = new DateTime(2023, 4, 14, 13, 55, 8, 882, DateTimeKind.Utc).AddTicks(3978),
                            Evaluation = 11,
                            FurnitureId = 46,
                            UserId = 3
                        },
                        new
                        {
                            Id = 55,
                            Comment = "Nobis id deserunt dolorem consequuntur sint ducimus. Sint et recusandae quaerat quod adipisci iste officiis praesentium. Qui molestiae sed et illo. Et et enim ex quam doloribus. Non sit dolorum ipsum quia.",
                            DateTime = new DateTime(2023, 4, 14, 13, 55, 8, 882, DateTimeKind.Utc).AddTicks(4096),
                            Evaluation = 3,
                            FurnitureId = 11,
                            UserId = 3
                        },
                        new
                        {
                            Id = 56,
                            Comment = "Cupiditate occaecati accusamus aliquam praesentium non aut dolor in reprehenderit. Autem incidunt voluptatibus enim praesentium laboriosam inventore. Adipisci distinctio qui quo voluptas dolores architecto a delectus cupiditate. Voluptatem atque beatae officiis quae non assumenda.",
                            DateTime = new DateTime(2023, 4, 14, 13, 55, 8, 882, DateTimeKind.Utc).AddTicks(4225),
                            Evaluation = 9,
                            FurnitureId = 12,
                            UserId = 1
                        },
                        new
                        {
                            Id = 57,
                            Comment = "Omnis similique laborum voluptas suscipit. Numquam asperiores voluptas nesciunt labore quod quas. Quod est voluptatem. Qui itaque pariatur distinctio suscipit. Impedit iste nihil odit velit. Reiciendis natus aliquid fuga ut sequi velit fugiat aut.",
                            DateTime = new DateTime(2023, 4, 14, 13, 55, 8, 882, DateTimeKind.Utc).AddTicks(4414),
                            Evaluation = 9,
                            FurnitureId = 15,
                            UserId = 2
                        },
                        new
                        {
                            Id = 58,
                            Comment = "Eum aperiam dolorem vel voluptas maiores voluptatem laboriosam aut. Qui maxime a ut aut ut corrupti est exercitationem. Non quos velit omnis aliquam quo et saepe debitis porro. Deleniti quo a dolorum iure laudantium. Expedita consequuntur voluptas perspiciatis ea enim soluta alias temporibus perferendis.",
                            DateTime = new DateTime(2023, 4, 14, 13, 55, 8, 882, DateTimeKind.Utc).AddTicks(4574),
                            Evaluation = 6,
                            FurnitureId = 12,
                            UserId = 2
                        },
                        new
                        {
                            Id = 59,
                            Comment = "Autem illo dolorem quae hic consequatur delectus est placeat saepe. Adipisci distinctio enim iusto cum non. Tenetur magni eligendi ut sed sed reprehenderit molestiae officia. Facere officiis et omnis vero.",
                            DateTime = new DateTime(2023, 4, 14, 13, 55, 8, 882, DateTimeKind.Utc).AddTicks(4682),
                            Evaluation = 8,
                            FurnitureId = 47,
                            UserId = 1
                        },
                        new
                        {
                            Id = 60,
                            Comment = "Provident inventore eligendi sed et quibusdam officiis veritatis. Modi molestiae voluptatum molestiae. Culpa doloribus ipsam culpa blanditiis recusandae. Beatae cum voluptatem assumenda. Saepe quaerat corrupti est accusamus atque consequatur qui. Aut neque quis magni non nihil ducimus totam molestiae.",
                            DateTime = new DateTime(2023, 4, 14, 13, 55, 8, 882, DateTimeKind.Utc).AddTicks(4827),
                            Evaluation = 9,
                            FurnitureId = 39,
                            UserId = 3
                        });
                });

            modelBuilder.Entity("Furniking.DAL.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f54406c2-41dc-4dfd-bdea-db6073d66bea",
                            Email = "user@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "USER@GMAIL.COM",
                            NormalizedUserName = "USER@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAED+iC9L8e9iGFkhx4oAxNEGAuBS3PVgssvAmS+sYY31GztzwSrvBWzQ82SZHtEFPMA==",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "user@gmail.com"
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e8006678-9197-4997-8962-6dba99d1b685",
                            Email = "moderator@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "MODERATOR@GMAIL.COM",
                            NormalizedUserName = "MODERATOR@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEEy6tSAcBir/YQqTrjMkkuxZ6emj4NYnUUfkdQXPCq/Hj4CoYrj8tBtj0y0g0hBn7A==",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "moderator@gmail.com"
                        },
                        new
                        {
                            Id = 3,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e8c7b865-ca2d-4553-81ac-9c05f61cb41a",
                            Email = "admin@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@GMAIL.COM",
                            NormalizedUserName = "ADMIN@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEHWMAJV6uY58j39+VygdlYtVbhoa7xVO4A/LyJ3P6sy6nkPe393o3N2D4r1YCR1yrA==",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "admin@gmail.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "User",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Moderator",
                            NormalizedName = "MODERATOR"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 3,
                            RoleId = 3
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Furniking.DAL.Entities.Furniture", b =>
                {
                    b.HasOne("Furniking.DAL.Entities.Category", "Category")
                        .WithMany("Furnitures")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Furniking.DAL.Entities.Image", b =>
                {
                    b.HasOne("Furniking.DAL.Entities.Furniture", null)
                        .WithMany("Images")
                        .HasForeignKey("FurnitureId");
                });

            modelBuilder.Entity("Furniking.DAL.Entities.Order", b =>
                {
                    b.HasOne("Furniking.DAL.Entities.Furniture", "Furniture")
                        .WithMany()
                        .HasForeignKey("FurnitureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Furniking.DAL.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Furniture");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Furniking.DAL.Entities.Review", b =>
                {
                    b.HasOne("Furniking.DAL.Entities.Furniture", "Furniture")
                        .WithMany("Reviews")
                        .HasForeignKey("FurnitureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Furniking.DAL.Entities.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Furniture");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Furniking.DAL.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Furniking.DAL.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Furniking.DAL.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Furniking.DAL.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Furniking.DAL.Entities.Category", b =>
                {
                    b.Navigation("Furnitures");
                });

            modelBuilder.Entity("Furniking.DAL.Entities.Furniture", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Furniking.DAL.Entities.User", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
