// <auto-generated />
using System;
using Furniking.DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Furniking.DAL.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230417190041_AddedFakeOrders")]
    partial class AddedFakeOrders
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Furniking.DAL.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Movies"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Beauty, Jewelery & Sports"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Shoes"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Beauty"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Tools"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Books"
                        });
                });

            modelBuilder.Entity("Furniking.DAL.Entities.Furniture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Furnitures");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 3,
                            Description = "Dolorem dolorem id quaerat quas incidunt iure numquam voluptatem. Quod adipisci rerum eos. Aut non ea impedit culpa. Minus placeat qui dolore nobis non sint. Magnam assumenda alias atque ducimus corrupti.",
                            Name = "Ergonomic Steel Cheese",
                            Price = 714.461616745433470m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 4,
                            Description = "At quia at facilis et. Dolores doloremque sed quo et non. Explicabo quam laboriosam perferendis. Sit accusamus qui assumenda commodi id quo odio autem.",
                            Name = "Gorgeous Plastic Tuna",
                            Price = 650.814796421125480m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 6,
                            Description = "Aut sunt perspiciatis animi quasi. Voluptatem blanditiis porro inventore recusandae omnis enim reprehenderit exercitationem. Aliquam laudantium et. Rerum dicta vel fugit recusandae dolor.",
                            Name = "Gorgeous Steel Car",
                            Price = 76.2118420359733480m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "Molestiae numquam nulla quibusdam esse placeat magnam pariatur. Illo corporis et nesciunt dolorem. Ex ut consequatur laborum blanditiis eos laborum autem omnis et. Saepe cumque ipsum beatae odio nihil earum voluptates. Quia ducimus ipsam voluptas quo. In commodi aperiam molestias enim.",
                            Name = "Fantastic Plastic Tuna",
                            Price = 777.491902325996650m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Description = "Ut repellendus ipsam. Dicta consequatur maxime at unde cum. Laborum aut eos magnam. Aut et tempora neque eveniet sunt veniam dolore omnis.",
                            Name = "Ergonomic Granite Pizza",
                            Price = 261.13919084013430m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            Description = "Dolorem in ea quia. Possimus commodi hic. Vero illum eveniet. Quam fuga ducimus cupiditate. Minima officia laborum aut.",
                            Name = "Unbranded Fresh Soap",
                            Price = 134.002516751178670m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            Description = "At ut non alias. Ducimus deleniti praesentium consequuntur autem ab perspiciatis ad quasi eaque. Eum vitae nisi et tempore. Cumque laboriosam dicta et illo. Tenetur fuga delectus aspernatur provident. Labore necessitatibus rerum eveniet non ut ratione maiores.",
                            Name = "Sleek Steel Tuna",
                            Price = 405.774495506554120m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            Description = "Ipsum fugit voluptatibus. Sed in corrupti enim officia. Voluptas reprehenderit quia quas quas dolorem hic perferendis sunt eum.",
                            Name = "Intelligent Steel Pants",
                            Price = 159.21915804930970m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            Description = "Delectus nemo fugit ipsa exercitationem perferendis consectetur repellendus. Voluptatibus temporibus voluptas consequuntur facere et exercitationem. Aut in itaque atque eveniet similique minima aperiam omnis non. Dolor et aut itaque quisquam saepe occaecati delectus voluptatum officiis.",
                            Name = "Sleek Fresh Shirt",
                            Price = 41.4305067115605610m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 5,
                            Description = "Nobis dignissimos architecto provident. Quas doloribus et. Velit quasi id fugiat consequatur provident aut. Consequatur aut officiis pariatur id. Ut et qui odit. Velit et voluptas ut est fugit ut voluptatem eos.",
                            Name = "Small Metal Chips",
                            Price = 408.106683580254220m
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 4,
                            Description = "Qui tempora rerum et et sunt omnis porro. Ut enim vitae. Voluptas aut ad qui.",
                            Name = "Rustic Wooden Keyboard",
                            Price = 147.693521630807560m
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 3,
                            Description = "Distinctio numquam libero at ipsam possimus facere quo. Ut repellendus nihil dolor et aliquid. Nesciunt quae temporibus facere aut ut odit exercitationem.",
                            Name = "Generic Cotton Keyboard",
                            Price = 525.813177430915210m
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 2,
                            Description = "Veniam numquam molestiae quia veniam. Voluptates in ex eius mollitia et libero inventore blanditiis aspernatur. Temporibus aut praesentium iure. Quaerat repudiandae qui aut quis sit. Doloremque est dolor accusamus veniam et quia magnam aperiam et.",
                            Name = "Handmade Frozen Hat",
                            Price = 722.661815305548460m
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 3,
                            Description = "Iusto labore veritatis ipsam similique adipisci natus. Accusamus et a. Vel quia sed.",
                            Name = "Handcrafted Cotton Hat",
                            Price = 584.586835356702520m
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 3,
                            Description = "Iste magnam nulla quia quisquam aliquam. Id rerum quisquam nihil. Tempore magni ut officia laudantium culpa et assumenda esse. Magnam et modi necessitatibus sit libero sequi. Explicabo temporibus eum. Nobis vel rem.",
                            Name = "Incredible Cotton Table",
                            Price = 453.62573194951990m
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 6,
                            Description = "Corporis doloremque quas ea. Voluptates eos et et sit. Sapiente repellat animi eveniet eum quasi ut qui fugiat et. Tenetur fuga ducimus qui fugit perferendis odit enim debitis veniam. Perferendis itaque adipisci iure omnis ex dolore dolore. Doloribus vel architecto quisquam.",
                            Name = "Incredible Fresh Keyboard",
                            Price = 817.925183082896230m
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 3,
                            Description = "Consequuntur laborum iure beatae debitis a eos. Nulla possimus corrupti eos est suscipit maiores nam nihil. Nostrum amet laboriosam officia in non. Unde qui quidem et.",
                            Name = "Awesome Metal Bike",
                            Price = 469.148209746530590m
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 4,
                            Description = "Unde sed molestias qui dolores qui. Rem et tempore iure iure eum. Pariatur adipisci earum neque. Ut non praesentium recusandae. Incidunt tempora omnis eum nostrum.",
                            Name = "Ergonomic Granite Fish",
                            Price = 417.512601603526870m
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 2,
                            Description = "Itaque rem eligendi necessitatibus amet molestiae molestiae. Neque laboriosam aut aperiam et enim. Consequatur non sapiente consectetur.",
                            Name = "Tasty Fresh Soap",
                            Price = 98.7827203417116160m
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 1,
                            Description = "Sit dicta et. Iste dolore explicabo voluptatem quaerat totam. Voluptatem ex quis aperiam totam dolorem. Quam occaecati voluptas sit ad et nihil accusamus qui voluptatem. Possimus aut nihil asperiores dolorem maxime. Ea qui repellendus natus itaque.",
                            Name = "Intelligent Rubber Ball",
                            Price = 359.69252862021940m
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 3,
                            Description = "Inventore porro perferendis cumque pariatur vel magnam neque vel qui. Nobis pariatur quasi. Et officia ab voluptas amet ut eligendi veritatis iusto. Vero culpa esse. Laborum ut non.",
                            Name = "Handcrafted Fresh Bike",
                            Price = 272.869536384414190m
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 1,
                            Description = "Laborum repudiandae culpa non culpa quisquam aut. Et quos excepturi beatae nulla rerum esse commodi. Et culpa mollitia doloribus quibusdam.",
                            Name = "Tasty Metal Fish",
                            Price = 839.805642808697170m
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 5,
                            Description = "Odit ipsum possimus ea voluptatum. Ad a neque deleniti quo alias ratione quo. Quos provident quas quia pariatur magni animi aperiam neque officia. Illum beatae nihil voluptas odit sint nobis.",
                            Name = "Intelligent Granite Bacon",
                            Price = 359.802114041429830m
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 6,
                            Description = "Qui ea velit ipsum. Mollitia voluptas vitae sint nam libero ut voluptatum similique. Quas eos deserunt vel. Saepe adipisci sed quo quis autem voluptatem autem tenetur animi.",
                            Name = "Incredible Soft Chicken",
                            Price = 740.821988052140050m
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 5,
                            Description = "Eos ullam asperiores quod id nesciunt. Expedita eos odio fugit quia aliquam sit neque eos. Veniam rerum et commodi quibusdam quasi. Ab consequuntur voluptatem non vel. Sit et quas aut minima exercitationem qui voluptatem nesciunt.",
                            Name = "Rustic Wooden Chicken",
                            Price = 47.5563073240017190m
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 6,
                            Description = "Cumque esse in asperiores distinctio et possimus vero. Veritatis tempora porro. Est quo eum nulla nemo aut magnam dolorum.",
                            Name = "Intelligent Concrete Pants",
                            Price = 159.875408345775310m
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 6,
                            Description = "Dicta amet error porro architecto vel molestiae ut aliquid qui. Totam odit est et. Quasi odit praesentium omnis.",
                            Name = "Refined Steel Gloves",
                            Price = 206.863160443894450m
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 2,
                            Description = "Unde excepturi quo. Suscipit quod pariatur est at et molestias rerum enim dolor. Voluptatum accusantium dolores facilis ratione aut dicta est quibusdam non. Sunt impedit magni pariatur quidem voluptatum quia voluptas aut. Rerum et quo est aliquam officiis. Porro natus totam ratione.",
                            Name = "Incredible Frozen Bike",
                            Price = 377.165895680508760m
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 3,
                            Description = "Beatae laudantium qui repudiandae voluptatem rem dolorem eos rerum. Eos aperiam occaecati. Ullam perspiciatis quo neque ullam sint necessitatibus aspernatur officiis aut. Laudantium porro sed ducimus. Perspiciatis nulla debitis enim magnam esse similique est.",
                            Name = "Sleek Plastic Cheese",
                            Price = 842.430422251313380m
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 6,
                            Description = "Non rerum neque quasi porro rerum ratione quos soluta. Voluptatibus deserunt pariatur cum natus facere delectus eligendi doloribus praesentium. Nesciunt quia id.",
                            Name = "Awesome Wooden Bike",
                            Price = 884.712643853720320m
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 5,
                            Description = "Et distinctio sed impedit sint iste magni qui aut. Aliquid adipisci qui ut dolorem quisquam. Veniam laborum deserunt. Et facere voluptas consequatur quod molestiae.",
                            Name = "Ergonomic Plastic Sausages",
                            Price = 195.175981533330370m
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 4,
                            Description = "Fugit non qui ut. Velit fugiat sapiente. Veritatis distinctio sapiente vel totam inventore quaerat et eaque voluptatem. Ex fuga voluptates minima nisi omnis consequuntur rerum asperiores.",
                            Name = "Awesome Fresh Towels",
                            Price = 483.25502701255240m
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 6,
                            Description = "Doloribus beatae labore esse omnis praesentium voluptatem est dolor voluptate. Sapiente magni deleniti totam temporibus et unde temporibus quos voluptatem. Et ut quasi necessitatibus ut quas.",
                            Name = "Licensed Fresh Ball",
                            Price = 497.765535930062830m
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 6,
                            Description = "Maiores et et aut saepe. Eius aspernatur recusandae nulla dolorem. Excepturi aut dolor unde voluptas laudantium distinctio debitis sed.",
                            Name = "Ergonomic Rubber Gloves",
                            Price = 455.704362381112120m
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 4,
                            Description = "Nemo quia consequatur est. Non deleniti doloribus suscipit ut saepe magni et aliquid eligendi. Et architecto blanditiis quos quo voluptatem. Aspernatur et veniam minus sed dolorem natus eos ea. Sit temporibus laborum deleniti sint nulla corporis. Autem non repellendus similique non architecto sit.",
                            Name = "Incredible Fresh Shoes",
                            Price = 759.673856361617110m
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 5,
                            Description = "Doloribus similique enim repellat nobis voluptatum. Neque est ea corrupti non repellendus error vitae earum iure. Voluptatem sapiente sint odit. Non quia non unde dolor ad quia nisi quis suscipit.",
                            Name = "Practical Soft Chair",
                            Price = 537.971333469251320m
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 2,
                            Description = "Qui harum iusto eum vitae alias nostrum dolorum cum. Illo similique aut nemo similique aut animi. Officiis voluptatum non dolorem rerum et veritatis fugit.",
                            Name = "Small Concrete Hat",
                            Price = 200.633238698650660m
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 2,
                            Description = "Quia autem quis. Qui ducimus sed et non aut nam quasi. Quos doloremque delectus et dignissimos laudantium facilis nobis ut. Maxime repellendus quia delectus consequatur eaque. Quidem officiis amet et iste non minima non perferendis. Possimus iste repellat veritatis eius.",
                            Name = "Handmade Steel Fish",
                            Price = 587.85921572607910m
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 1,
                            Description = "Enim eius iure nihil tenetur perspiciatis rerum. Deleniti enim aut quasi totam. Aut ad itaque aspernatur nobis quo molestiae dolorem necessitatibus. Ut ea cupiditate sed. Nisi est possimus. Ipsa id ut.",
                            Name = "Generic Wooden Ball",
                            Price = 121.539898012550590m
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 5,
                            Description = "Dignissimos tempore non mollitia molestiae nihil perferendis est veritatis. Consequuntur neque aut voluptas quaerat cupiditate deserunt. Nobis modi eos. Consequuntur illo nihil consectetur voluptates neque aut quia. Iure tempore aliquid ducimus blanditiis ut voluptas aspernatur et accusantium. Qui nesciunt necessitatibus aut et rerum vero est.",
                            Name = "Tasty Soft Gloves",
                            Price = 389.064030791196520m
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 4,
                            Description = "Debitis ipsum labore autem pariatur aut itaque. Quod quos placeat aut et omnis eum et. Velit atque beatae delectus. Perspiciatis est enim nemo. Quod incidunt placeat qui. Nam et explicabo deserunt vero nihil quia est.",
                            Name = "Generic Granite Chicken",
                            Price = 648.648024661768330m
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 2,
                            Description = "Illo iste quibusdam. Suscipit consectetur cumque culpa quo et. Occaecati perspiciatis nobis velit quam doloribus aliquid. Numquam eveniet praesentium. Veritatis deleniti voluptatem quo. Praesentium perferendis sequi earum sint aliquam.",
                            Name = "Rustic Cotton Fish",
                            Price = 154.147735058398390m
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 4,
                            Description = "Quia vel sapiente enim amet harum sunt ducimus sunt nesciunt. Cum ut sequi. Voluptatem id aut enim deleniti voluptatem quia. Voluptatum id consequatur quis sed perferendis maiores optio.",
                            Name = "Practical Plastic Bacon",
                            Price = 548.208269583158350m
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 3,
                            Description = "Exercitationem reprehenderit fuga doloribus quis at fugit ut aut. Omnis et eligendi. Quos aut cumque velit cum. Nihil dolor nisi omnis et aut.",
                            Name = "Gorgeous Rubber Car",
                            Price = 469.202228430287320m
                        },
                        new
                        {
                            Id = 45,
                            CategoryId = 5,
                            Description = "Maiores soluta et. Ad facere pariatur commodi laboriosam aperiam consectetur maiores ratione. Autem ab in unde autem. Repellendus ipsa sed quae quasi iste. Iure et dolor soluta sint.",
                            Name = "Ergonomic Plastic Towels",
                            Price = 48.3001001031603790m
                        },
                        new
                        {
                            Id = 46,
                            CategoryId = 5,
                            Description = "Ducimus eum consequuntur consequatur ratione voluptatem. Quis consequatur sunt dignissimos excepturi maxime quia. Voluptatem earum natus.",
                            Name = "Handmade Metal Towels",
                            Price = 876.887589230615260m
                        },
                        new
                        {
                            Id = 47,
                            CategoryId = 6,
                            Description = "Aliquid tempore rerum quia. Minus deleniti nihil quia non sunt distinctio. Ut saepe quas ut praesentium ullam ipsum nam. Enim non natus voluptas beatae eligendi quis nihil sapiente quis. Quia autem deleniti dolorum sapiente modi.",
                            Name = "Handmade Granite Shoes",
                            Price = 364.30728545147320m
                        },
                        new
                        {
                            Id = 48,
                            CategoryId = 5,
                            Description = "Ut deserunt voluptatibus minima blanditiis accusantium nesciunt. Dolores velit ea sit voluptas illum et. Ab esse delectus sed minima totam dolor esse rerum. Ut earum quia sunt ipsam. Reprehenderit a et.",
                            Name = "Ergonomic Rubber Ball",
                            Price = 494.905089975755680m
                        },
                        new
                        {
                            Id = 49,
                            CategoryId = 1,
                            Description = "Quo vel sed animi velit ea nihil dolor ipsa. Enim suscipit quia quibusdam. Similique reprehenderit voluptatem temporibus eius commodi.",
                            Name = "Ergonomic Concrete Sausages",
                            Price = 925.404324184825750m
                        },
                        new
                        {
                            Id = 50,
                            CategoryId = 5,
                            Description = "Architecto a neque doloremque. Totam possimus quibusdam exercitationem quis odit eum ut doloremque provident. Est inventore harum. Beatae ratione cumque aut ratione asperiores dignissimos repellendus.",
                            Name = "Incredible Rubber Bacon",
                            Price = 290.497724488609210m
                        });
                });

            modelBuilder.Entity("Furniking.DAL.Entities.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FurnitureId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FurnitureId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("Furniking.DAL.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfOrder")
                        .HasColumnType("datetime2");

                    b.Property<int>("FurnitureId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FurnitureId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Count = 1,
                            DateOfOrder = new DateTime(2023, 3, 19, 4, 11, 55, 228, DateTimeKind.Unspecified).AddTicks(5825),
                            FurnitureId = 26,
                            UserId = 3
                        },
                        new
                        {
                            Id = 2,
                            Count = 4,
                            DateOfOrder = new DateTime(2023, 4, 11, 15, 31, 2, 526, DateTimeKind.Unspecified).AddTicks(6767),
                            FurnitureId = 37,
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            Count = 2,
                            DateOfOrder = new DateTime(2023, 4, 1, 16, 28, 3, 393, DateTimeKind.Unspecified).AddTicks(1365),
                            FurnitureId = 20,
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            Count = 2,
                            DateOfOrder = new DateTime(2023, 3, 17, 15, 28, 59, 874, DateTimeKind.Unspecified).AddTicks(1132),
                            FurnitureId = 38,
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            Count = 1,
                            DateOfOrder = new DateTime(2023, 4, 13, 11, 57, 26, 773, DateTimeKind.Unspecified).AddTicks(2913),
                            FurnitureId = 18,
                            UserId = 3
                        },
                        new
                        {
                            Id = 6,
                            Count = 1,
                            DateOfOrder = new DateTime(2023, 4, 2, 10, 0, 35, 245, DateTimeKind.Unspecified).AddTicks(3564),
                            FurnitureId = 36,
                            UserId = 2
                        },
                        new
                        {
                            Id = 7,
                            Count = 3,
                            DateOfOrder = new DateTime(2023, 4, 5, 5, 41, 16, 627, DateTimeKind.Unspecified).AddTicks(3057),
                            FurnitureId = 38,
                            UserId = 3
                        },
                        new
                        {
                            Id = 8,
                            Count = 2,
                            DateOfOrder = new DateTime(2023, 3, 24, 14, 28, 16, 991, DateTimeKind.Unspecified).AddTicks(3561),
                            FurnitureId = 11,
                            UserId = 3
                        },
                        new
                        {
                            Id = 9,
                            Count = 3,
                            DateOfOrder = new DateTime(2023, 4, 1, 1, 7, 51, 160, DateTimeKind.Unspecified).AddTicks(9815),
                            FurnitureId = 39,
                            UserId = 1
                        },
                        new
                        {
                            Id = 10,
                            Count = 1,
                            DateOfOrder = new DateTime(2023, 4, 1, 0, 1, 50, 206, DateTimeKind.Unspecified).AddTicks(8857),
                            FurnitureId = 25,
                            UserId = 2
                        },
                        new
                        {
                            Id = 11,
                            Count = 4,
                            DateOfOrder = new DateTime(2023, 3, 30, 23, 43, 41, 908, DateTimeKind.Unspecified).AddTicks(9056),
                            FurnitureId = 15,
                            UserId = 1
                        },
                        new
                        {
                            Id = 12,
                            Count = 4,
                            DateOfOrder = new DateTime(2023, 3, 26, 3, 18, 55, 125, DateTimeKind.Unspecified).AddTicks(7335),
                            FurnitureId = 43,
                            UserId = 2
                        },
                        new
                        {
                            Id = 13,
                            Count = 1,
                            DateOfOrder = new DateTime(2023, 4, 12, 10, 2, 13, 974, DateTimeKind.Unspecified).AddTicks(2114),
                            FurnitureId = 31,
                            UserId = 2
                        },
                        new
                        {
                            Id = 14,
                            Count = 3,
                            DateOfOrder = new DateTime(2023, 4, 1, 9, 32, 32, 824, DateTimeKind.Unspecified).AddTicks(4670),
                            FurnitureId = 27,
                            UserId = 1
                        },
                        new
                        {
                            Id = 15,
                            Count = 4,
                            DateOfOrder = new DateTime(2023, 3, 19, 2, 2, 28, 257, DateTimeKind.Unspecified).AddTicks(1889),
                            FurnitureId = 9,
                            UserId = 3
                        },
                        new
                        {
                            Id = 16,
                            Count = 1,
                            DateOfOrder = new DateTime(2023, 3, 29, 23, 2, 54, 906, DateTimeKind.Unspecified).AddTicks(5666),
                            FurnitureId = 1,
                            UserId = 2
                        },
                        new
                        {
                            Id = 17,
                            Count = 5,
                            DateOfOrder = new DateTime(2023, 3, 17, 14, 40, 38, 212, DateTimeKind.Unspecified).AddTicks(5221),
                            FurnitureId = 37,
                            UserId = 3
                        },
                        new
                        {
                            Id = 18,
                            Count = 4,
                            DateOfOrder = new DateTime(2023, 3, 28, 6, 51, 24, 250, DateTimeKind.Unspecified).AddTicks(8342),
                            FurnitureId = 36,
                            UserId = 3
                        },
                        new
                        {
                            Id = 19,
                            Count = 3,
                            DateOfOrder = new DateTime(2023, 3, 28, 14, 43, 56, 276, DateTimeKind.Unspecified).AddTicks(7467),
                            FurnitureId = 33,
                            UserId = 2
                        },
                        new
                        {
                            Id = 20,
                            Count = 2,
                            DateOfOrder = new DateTime(2023, 3, 19, 8, 19, 53, 724, DateTimeKind.Unspecified).AddTicks(7938),
                            FurnitureId = 15,
                            UserId = 1
                        },
                        new
                        {
                            Id = 21,
                            Count = 2,
                            DateOfOrder = new DateTime(2023, 4, 13, 6, 34, 59, 54, DateTimeKind.Unspecified).AddTicks(2060),
                            FurnitureId = 28,
                            UserId = 2
                        },
                        new
                        {
                            Id = 22,
                            Count = 4,
                            DateOfOrder = new DateTime(2023, 3, 19, 4, 27, 38, 424, DateTimeKind.Unspecified).AddTicks(1912),
                            FurnitureId = 2,
                            UserId = 3
                        },
                        new
                        {
                            Id = 23,
                            Count = 3,
                            DateOfOrder = new DateTime(2023, 4, 8, 4, 26, 14, 380, DateTimeKind.Unspecified).AddTicks(2294),
                            FurnitureId = 47,
                            UserId = 1
                        },
                        new
                        {
                            Id = 24,
                            Count = 3,
                            DateOfOrder = new DateTime(2023, 3, 25, 9, 38, 8, 363, DateTimeKind.Unspecified).AddTicks(7858),
                            FurnitureId = 15,
                            UserId = 2
                        },
                        new
                        {
                            Id = 25,
                            Count = 1,
                            DateOfOrder = new DateTime(2023, 3, 24, 21, 42, 53, 872, DateTimeKind.Unspecified).AddTicks(8187),
                            FurnitureId = 31,
                            UserId = 2
                        },
                        new
                        {
                            Id = 26,
                            Count = 3,
                            DateOfOrder = new DateTime(2023, 4, 5, 19, 22, 27, 465, DateTimeKind.Unspecified).AddTicks(7339),
                            FurnitureId = 41,
                            UserId = 1
                        },
                        new
                        {
                            Id = 27,
                            Count = 1,
                            DateOfOrder = new DateTime(2023, 4, 14, 22, 16, 57, 585, DateTimeKind.Unspecified).AddTicks(9348),
                            FurnitureId = 4,
                            UserId = 1
                        },
                        new
                        {
                            Id = 28,
                            Count = 5,
                            DateOfOrder = new DateTime(2023, 3, 28, 16, 58, 15, 83, DateTimeKind.Unspecified).AddTicks(893),
                            FurnitureId = 32,
                            UserId = 1
                        },
                        new
                        {
                            Id = 29,
                            Count = 5,
                            DateOfOrder = new DateTime(2023, 4, 5, 23, 51, 22, 963, DateTimeKind.Unspecified).AddTicks(6571),
                            FurnitureId = 11,
                            UserId = 3
                        },
                        new
                        {
                            Id = 30,
                            Count = 5,
                            DateOfOrder = new DateTime(2023, 4, 10, 16, 5, 48, 554, DateTimeKind.Unspecified).AddTicks(1077),
                            FurnitureId = 38,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("Furniking.DAL.Entities.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Evaluation")
                        .HasColumnType("int");

                    b.Property<int>("FurnitureId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FurnitureId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comment = "Est excepturi quibusdam. Dolorem id quaerat quas incidunt iure numquam voluptatem dolores. Adipisci rerum eos ea aut non ea impedit.",
                            DateTime = new DateTime(2023, 4, 5, 5, 41, 16, 627, DateTimeKind.Unspecified).AddTicks(3057),
                            Evaluation = 7,
                            FurnitureId = 38,
                            UserId = 3
                        },
                        new
                        {
                            Id = 2,
                            Comment = "Nobis non sint atque. Assumenda alias atque ducimus corrupti. Qui enim veniam quidem exercitationem quis at quia. Facilis et odio dolores doloremque sed quo et non.",
                            DateTime = new DateTime(2023, 3, 19, 22, 32, 23, 548, DateTimeKind.Unspecified).AddTicks(4042),
                            Evaluation = 2,
                            FurnitureId = 17,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            Comment = "Sit accusamus qui assumenda commodi id quo odio autem. Et quaerat architecto quasi quis magnam aut sunt. Animi quasi assumenda voluptatem blanditiis porro inventore.",
                            DateTime = new DateTime(2023, 4, 3, 3, 36, 58, 579, DateTimeKind.Unspecified).AddTicks(2015),
                            Evaluation = 11,
                            FurnitureId = 20,
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            Comment = "Aliquam laudantium et. Rerum dicta vel fugit recusandae dolor. Pariatur vel minima. Asperiores facilis molestiae numquam nulla quibusdam esse placeat.",
                            DateTime = new DateTime(2023, 4, 12, 7, 28, 44, 443, DateTimeKind.Unspecified).AddTicks(6330),
                            Evaluation = 3,
                            FurnitureId = 3,
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            Comment = "Nesciunt dolorem voluptatibus ex ut consequatur laborum blanditiis eos. Autem omnis et libero saepe cumque ipsum. Odio nihil earum. Nisi quia ducimus ipsam voluptas quo commodi in commodi aperiam.",
                            DateTime = new DateTime(2023, 3, 26, 15, 23, 40, 579, DateTimeKind.Unspecified).AddTicks(8482),
                            Evaluation = 6,
                            FurnitureId = 1,
                            UserId = 3
                        },
                        new
                        {
                            Id = 6,
                            Comment = "Quo enim voluptatem ut repellendus ipsam. Dicta consequatur maxime at unde cum. Laborum aut eos magnam.",
                            DateTime = new DateTime(2023, 4, 10, 23, 54, 56, 654, DateTimeKind.Unspecified).AddTicks(6325),
                            Evaluation = 10,
                            FurnitureId = 12,
                            UserId = 3
                        },
                        new
                        {
                            Id = 7,
                            Comment = "Sunt veniam dolore omnis aliquam sed saepe rerum et cum. Dolorem in ea quia. Possimus commodi hic.",
                            DateTime = new DateTime(2023, 4, 12, 14, 58, 48, 838, DateTimeKind.Unspecified).AddTicks(695),
                            Evaluation = 2,
                            FurnitureId = 45,
                            UserId = 3
                        },
                        new
                        {
                            Id = 8,
                            Comment = "Fuga ducimus cupiditate amet minima officia. Aut consequuntur ducimus et et expedita fugiat. At ut non alias.",
                            DateTime = new DateTime(2023, 3, 30, 22, 5, 16, 305, DateTimeKind.Unspecified).AddTicks(6103),
                            Evaluation = 11,
                            FurnitureId = 24,
                            UserId = 2
                        },
                        new
                        {
                            Id = 9,
                            Comment = "Ab perspiciatis ad quasi eaque ad eum vitae nisi. Tempore consequatur cumque laboriosam dicta et illo ad. Fuga delectus aspernatur provident nihil labore necessitatibus rerum eveniet non.",
                            DateTime = new DateTime(2023, 3, 21, 12, 4, 41, 809, DateTimeKind.Unspecified).AddTicks(5559),
                            Evaluation = 11,
                            FurnitureId = 20,
                            UserId = 3
                        },
                        new
                        {
                            Id = 10,
                            Comment = "Quae suscipit eaque dicta. Fugit voluptatibus enim sed. Corrupti enim officia repudiandae voluptas reprehenderit quia. Quas dolorem hic perferendis sunt eum voluptatem.",
                            DateTime = new DateTime(2023, 4, 1, 2, 40, 18, 873, DateTimeKind.Unspecified).AddTicks(6811),
                            Evaluation = 5,
                            FurnitureId = 19,
                            UserId = 3
                        },
                        new
                        {
                            Id = 11,
                            Comment = "Delectus nemo fugit ipsa exercitationem perferendis consectetur repellendus. Voluptatibus temporibus voluptas consequuntur facere et exercitationem. Aut in itaque atque eveniet similique minima aperiam omnis non. Dolor et aut itaque quisquam saepe occaecati delectus voluptatum officiis.",
                            DateTime = new DateTime(2023, 3, 28, 16, 34, 9, 504, DateTimeKind.Unspecified).AddTicks(3675),
                            Evaluation = 1,
                            FurnitureId = 36,
                            UserId = 1
                        },
                        new
                        {
                            Id = 12,
                            Comment = "Neque nobis dignissimos architecto provident explicabo quas doloribus et. Velit quasi id fugiat consequatur provident aut. Consequatur aut officiis pariatur id. Ut et qui odit. Velit et voluptas ut est fugit ut voluptatem eos. Est quia sed eos dolor eligendi.",
                            DateTime = new DateTime(2023, 3, 24, 1, 44, 56, 397, DateTimeKind.Unspecified).AddTicks(9572),
                            Evaluation = 5,
                            FurnitureId = 44,
                            UserId = 2
                        },
                        new
                        {
                            Id = 13,
                            Comment = "Omnis porro fugit ut enim vitae non. Aut ad qui eos animi dolorum iusto dolorem perferendis. Distinctio numquam libero at ipsam possimus facere quo. Ut repellendus nihil dolor et aliquid.",
                            DateTime = new DateTime(2023, 3, 21, 23, 21, 47, 797, DateTimeKind.Unspecified).AddTicks(226),
                            Evaluation = 7,
                            FurnitureId = 40,
                            UserId = 1
                        },
                        new
                        {
                            Id = 14,
                            Comment = "Ut odit exercitationem occaecati velit est voluptatibus sed natus. Veniam numquam molestiae quia veniam. Voluptates in ex eius mollitia et libero inventore blanditiis aspernatur. Temporibus aut praesentium iure. Quaerat repudiandae qui aut quis sit. Doloremque est dolor accusamus veniam et quia magnam aperiam et.",
                            DateTime = new DateTime(2023, 3, 24, 17, 32, 52, 249, DateTimeKind.Unspecified).AddTicks(918),
                            Evaluation = 8,
                            FurnitureId = 22,
                            UserId = 2
                        },
                        new
                        {
                            Id = 15,
                            Comment = "Laborum iusto labore veritatis. Similique adipisci natus aspernatur accusamus. A aut vel quia sed culpa dolores quia dignissimos quam. Iure iste magnam nulla quia quisquam aliquam non id. Quisquam nihil dolor tempore magni ut officia laudantium culpa et.",
                            DateTime = new DateTime(2023, 3, 29, 20, 8, 49, 33, DateTimeKind.Unspecified).AddTicks(3475),
                            Evaluation = 9,
                            FurnitureId = 13,
                            UserId = 2
                        },
                        new
                        {
                            Id = 16,
                            Comment = "Necessitatibus sit libero sequi. Explicabo temporibus eum. Nobis vel rem.",
                            DateTime = new DateTime(2023, 3, 31, 14, 57, 42, 936, DateTimeKind.Unspecified).AddTicks(3147),
                            Evaluation = 5,
                            FurnitureId = 45,
                            UserId = 1
                        },
                        new
                        {
                            Id = 17,
                            Comment = "Labore corporis doloremque quas ea ipsam voluptates eos et et. Aut sapiente repellat. Eveniet eum quasi ut qui fugiat et.",
                            DateTime = new DateTime(2023, 4, 15, 13, 13, 8, 280, DateTimeKind.Unspecified).AddTicks(3841),
                            Evaluation = 11,
                            FurnitureId = 23,
                            UserId = 2
                        },
                        new
                        {
                            Id = 18,
                            Comment = "Perferendis odit enim. Veniam et perferendis itaque adipisci iure omnis ex dolore dolore. Doloribus vel architecto quisquam. Officiis omnis rerum ut ut unde consequuntur laborum iure.",
                            DateTime = new DateTime(2023, 4, 13, 5, 40, 37, 780, DateTimeKind.Unspecified).AddTicks(8457),
                            Evaluation = 1,
                            FurnitureId = 44,
                            UserId = 3
                        },
                        new
                        {
                            Id = 19,
                            Comment = "Possimus corrupti eos est suscipit maiores nam nihil dignissimos. Amet laboriosam officia in non. Unde qui quidem et. Totam beatae non id et in. Sed molestias qui dolores qui in rem. Tempore iure iure eum quia pariatur.",
                            DateTime = new DateTime(2023, 4, 15, 4, 54, 34, 964, DateTimeKind.Unspecified).AddTicks(2469),
                            Evaluation = 3,
                            FurnitureId = 11,
                            UserId = 1
                        },
                        new
                        {
                            Id = 20,
                            Comment = "Praesentium recusandae voluptas incidunt. Omnis eum nostrum velit. Tenetur fugiat qui fugit qui itaque rem. Necessitatibus amet molestiae molestiae totam neque laboriosam aut. Et enim dolores.",
                            DateTime = new DateTime(2023, 4, 2, 10, 24, 27, 657, DateTimeKind.Unspecified).AddTicks(1007),
                            Evaluation = 5,
                            FurnitureId = 10,
                            UserId = 3
                        },
                        new
                        {
                            Id = 21,
                            Comment = "Dolor officia ut eveniet. Sit dicta et. Iste dolore explicabo voluptatem quaerat totam.",
                            DateTime = new DateTime(2023, 3, 26, 20, 23, 54, 339, DateTimeKind.Unspecified).AddTicks(5620),
                            Evaluation = 6,
                            FurnitureId = 15,
                            UserId = 2
                        },
                        new
                        {
                            Id = 22,
                            Comment = "Dolorem necessitatibus quam occaecati voluptas sit. Et nihil accusamus qui voluptatem. Possimus aut nihil asperiores dolorem maxime.",
                            DateTime = new DateTime(2023, 3, 29, 12, 16, 1, 892, DateTimeKind.Unspecified).AddTicks(2886),
                            Evaluation = 4,
                            FurnitureId = 40,
                            UserId = 3
                        },
                        new
                        {
                            Id = 23,
                            Comment = "Aliquid perferendis nam saepe non id ut inventore porro perferendis. Pariatur vel magnam neque vel qui aut nobis. Quasi eos et officia ab voluptas amet ut eligendi. Iusto aut vero. Esse consequatur laborum ut non ut quos.",
                            DateTime = new DateTime(2023, 4, 7, 7, 0, 42, 730, DateTimeKind.Unspecified).AddTicks(824),
                            Evaluation = 11,
                            FurnitureId = 10,
                            UserId = 3
                        },
                        new
                        {
                            Id = 24,
                            Comment = "Repudiandae culpa non culpa quisquam aut quo. Quos excepturi beatae nulla rerum esse commodi commodi et. Mollitia doloribus quibusdam quo nesciunt velit rem. Quam ea odit ipsum possimus ea voluptatum quo ad. Neque deleniti quo alias ratione quo et quos provident quas.",
                            DateTime = new DateTime(2023, 4, 12, 7, 32, 42, 306, DateTimeKind.Unspecified).AddTicks(725),
                            Evaluation = 4,
                            FurnitureId = 31,
                            UserId = 1
                        },
                        new
                        {
                            Id = 25,
                            Comment = "Officia qui illum beatae. Voluptas odit sint nobis aliquid omnis. Facere cum consequatur quia qui.",
                            DateTime = new DateTime(2023, 3, 23, 5, 0, 24, 645, DateTimeKind.Unspecified).AddTicks(2714),
                            Evaluation = 5,
                            FurnitureId = 44,
                            UserId = 1
                        },
                        new
                        {
                            Id = 26,
                            Comment = "Vitae sint nam libero ut voluptatum similique incidunt quas. Deserunt vel saepe saepe. Sed quo quis autem. Autem tenetur animi id at. Ratione nihil est in.",
                            DateTime = new DateTime(2023, 3, 26, 5, 31, 59, 150, DateTimeKind.Unspecified).AddTicks(8282),
                            Evaluation = 10,
                            FurnitureId = 38,
                            UserId = 3
                        },
                        new
                        {
                            Id = 27,
                            Comment = "Possimus expedita eos odio. Quia aliquam sit. Eos voluptatum veniam rerum. Commodi quibusdam quasi minima ab consequuntur voluptatem non vel. Sit et quas aut minima exercitationem qui voluptatem nesciunt.",
                            DateTime = new DateTime(2023, 4, 10, 5, 42, 55, 89, DateTimeKind.Unspecified).AddTicks(4553),
                            Evaluation = 1,
                            FurnitureId = 12,
                            UserId = 1
                        },
                        new
                        {
                            Id = 28,
                            Comment = "Libero cumque esse in. Distinctio et possimus vero eaque veritatis tempora porro eligendi est. Eum nulla nemo aut magnam dolorum voluptatem et et. Quia quia voluptates.",
                            DateTime = new DateTime(2023, 3, 22, 17, 29, 3, 364, DateTimeKind.Unspecified).AddTicks(2740),
                            Evaluation = 1,
                            FurnitureId = 36,
                            UserId = 2
                        },
                        new
                        {
                            Id = 29,
                            Comment = "Molestiae ut aliquid qui ipsum totam. Est et numquam. Odit praesentium omnis.",
                            DateTime = new DateTime(2023, 4, 15, 14, 11, 34, 588, DateTimeKind.Unspecified).AddTicks(9875),
                            Evaluation = 3,
                            FurnitureId = 47,
                            UserId = 2
                        },
                        new
                        {
                            Id = 30,
                            Comment = "Ab unde excepturi quo tenetur suscipit quod pariatur est at. Molestias rerum enim dolor itaque voluptatum. Dolores facilis ratione.",
                            DateTime = new DateTime(2023, 3, 19, 15, 33, 17, 255, DateTimeKind.Unspecified).AddTicks(5779),
                            Evaluation = 11,
                            FurnitureId = 40,
                            UserId = 3
                        },
                        new
                        {
                            Id = 31,
                            Comment = "Sunt impedit magni pariatur quidem voluptatum quia voluptas aut. Rerum et quo est aliquam officiis. Porro natus totam ratione. Voluptatem deleniti nemo autem animi. Beatae laudantium qui repudiandae voluptatem rem dolorem eos rerum. Eos aperiam occaecati.",
                            DateTime = new DateTime(2023, 3, 26, 7, 24, 30, 142, DateTimeKind.Unspecified).AddTicks(1758),
                            Evaluation = 11,
                            FurnitureId = 42,
                            UserId = 2
                        },
                        new
                        {
                            Id = 32,
                            Comment = "Sint necessitatibus aspernatur officiis aut. Laudantium porro sed ducimus. Perspiciatis nulla debitis enim magnam esse similique est.",
                            DateTime = new DateTime(2023, 3, 28, 8, 22, 6, 748, DateTimeKind.Unspecified).AddTicks(6951),
                            Evaluation = 10,
                            FurnitureId = 6,
                            UserId = 2
                        },
                        new
                        {
                            Id = 33,
                            Comment = "At non rerum neque. Porro rerum ratione. Soluta sint voluptatibus deserunt pariatur cum.",
                            DateTime = new DateTime(2023, 4, 9, 8, 37, 37, 536, DateTimeKind.Unspecified).AddTicks(4049),
                            Evaluation = 7,
                            FurnitureId = 35,
                            UserId = 3
                        },
                        new
                        {
                            Id = 34,
                            Comment = "Perferendis nesciunt quia id rerum reiciendis. Voluptatem recusandae ea. Et distinctio sed impedit sint iste magni qui aut. Aliquid adipisci qui ut dolorem quisquam. Veniam laborum deserunt. Et facere voluptas consequatur quod molestiae.",
                            DateTime = new DateTime(2023, 4, 8, 21, 18, 52, 100, DateTimeKind.Unspecified).AddTicks(307),
                            Evaluation = 3,
                            FurnitureId = 42,
                            UserId = 2
                        },
                        new
                        {
                            Id = 35,
                            Comment = "Qui fugit non qui ut. Velit fugiat sapiente. Veritatis distinctio sapiente vel totam inventore quaerat et eaque voluptatem. Ex fuga voluptates minima nisi omnis consequuntur rerum asperiores. Similique autem debitis magnam sequi eveniet.",
                            DateTime = new DateTime(2023, 3, 19, 9, 48, 0, 452, DateTimeKind.Unspecified).AddTicks(7089),
                            Evaluation = 11,
                            FurnitureId = 21,
                            UserId = 1
                        },
                        new
                        {
                            Id = 36,
                            Comment = "Voluptatem est dolor voluptate non sapiente. Deleniti totam temporibus et. Temporibus quos voluptatem qui et ut quasi. Ut quas quos accusamus vitae natus enim nesciunt enim maiores. Et aut saepe commodi eius aspernatur recusandae nulla dolorem. Excepturi aut dolor unde voluptas laudantium distinctio debitis sed.",
                            DateTime = new DateTime(2023, 4, 16, 3, 17, 33, 602, DateTimeKind.Unspecified).AddTicks(3776),
                            Evaluation = 5,
                            FurnitureId = 44,
                            UserId = 2
                        },
                        new
                        {
                            Id = 37,
                            Comment = "Velit nemo quia consequatur est ut non deleniti doloribus. Ut saepe magni et aliquid. Quam et architecto blanditiis quos quo voluptatem possimus. Et veniam minus.",
                            DateTime = new DateTime(2023, 4, 11, 15, 29, 31, 217, DateTimeKind.Unspecified).AddTicks(1740),
                            Evaluation = 6,
                            FurnitureId = 7,
                            UserId = 2
                        },
                        new
                        {
                            Id = 38,
                            Comment = "Sit temporibus laborum deleniti sint nulla corporis. Autem non repellendus similique non architecto sit. Omnis odio quibusdam aperiam ut corrupti doloribus similique enim. Nobis voluptatum rerum neque est ea corrupti non repellendus error.",
                            DateTime = new DateTime(2023, 4, 15, 5, 6, 29, 538, DateTimeKind.Unspecified).AddTicks(1223),
                            Evaluation = 1,
                            FurnitureId = 12,
                            UserId = 2
                        },
                        new
                        {
                            Id = 39,
                            Comment = "Sint odit ut non quia non unde dolor ad quia. Quis suscipit provident et ipsa. Occaecati nesciunt eum qui.",
                            DateTime = new DateTime(2023, 3, 30, 13, 38, 8, 752, DateTimeKind.Unspecified).AddTicks(7128),
                            Evaluation = 7,
                            FurnitureId = 5,
                            UserId = 2
                        },
                        new
                        {
                            Id = 40,
                            Comment = "Dolorum cum est illo similique. Nemo similique aut animi maxime officiis voluptatum non dolorem rerum. Veritatis fugit consectetur magnam omnis eaque id et.",
                            DateTime = new DateTime(2023, 3, 27, 1, 37, 18, 211, DateTimeKind.Unspecified).AddTicks(4661),
                            Evaluation = 1,
                            FurnitureId = 15,
                            UserId = 2
                        },
                        new
                        {
                            Id = 41,
                            Comment = "Ducimus sed et non aut nam quasi. Quos doloremque delectus et dignissimos laudantium facilis nobis ut. Maxime repellendus quia delectus consequatur eaque. Quidem officiis amet et iste non minima non perferendis. Possimus iste repellat veritatis eius.",
                            DateTime = new DateTime(2023, 3, 25, 21, 34, 13, 529, DateTimeKind.Unspecified).AddTicks(5937),
                            Evaluation = 7,
                            FurnitureId = 9,
                            UserId = 2
                        },
                        new
                        {
                            Id = 42,
                            Comment = "Deserunt enim eius iure nihil tenetur perspiciatis rerum quaerat. Enim aut quasi totam autem aut. Itaque aspernatur nobis quo molestiae. Necessitatibus magni ut ea.",
                            DateTime = new DateTime(2023, 3, 23, 5, 53, 40, 915, DateTimeKind.Unspecified).AddTicks(6448),
                            Evaluation = 6,
                            FurnitureId = 18,
                            UserId = 1
                        },
                        new
                        {
                            Id = 43,
                            Comment = "Sit ipsa id ut fugit magni reiciendis id quia. Vel dignissimos tempore non mollitia molestiae nihil perferendis est. Mollitia consequuntur neque. Voluptas quaerat cupiditate. Sit nobis modi eos nam consequuntur illo.",
                            DateTime = new DateTime(2023, 3, 22, 21, 0, 31, 28, DateTimeKind.Unspecified).AddTicks(5935),
                            Evaluation = 5,
                            FurnitureId = 9,
                            UserId = 3
                        },
                        new
                        {
                            Id = 44,
                            Comment = "Hic iure tempore. Ducimus blanditiis ut voluptas aspernatur. Accusantium et qui nesciunt necessitatibus aut. Rerum vero est eum quisquam rerum. Cum dolor unde debitis ipsum labore autem. Aut itaque est quod quos placeat aut et omnis.",
                            DateTime = new DateTime(2023, 4, 14, 12, 52, 51, 446, DateTimeKind.Unspecified).AddTicks(9112),
                            Evaluation = 10,
                            FurnitureId = 10,
                            UserId = 1
                        },
                        new
                        {
                            Id = 45,
                            Comment = "Delectus neque perspiciatis. Enim nemo velit quod incidunt placeat qui cum. Et explicabo deserunt vero nihil quia est facilis. Voluptatem iure placeat possimus illo illo iste.",
                            DateTime = new DateTime(2023, 3, 31, 1, 37, 11, 622, DateTimeKind.Unspecified).AddTicks(2039),
                            Evaluation = 9,
                            FurnitureId = 10,
                            UserId = 2
                        },
                        new
                        {
                            Id = 46,
                            Comment = "Quo et unde occaecati perspiciatis nobis velit. Doloribus aliquid architecto numquam eveniet praesentium. Veritatis deleniti voluptatem quo. Praesentium perferendis sequi earum sint aliquam. Amet et exercitationem aut.",
                            DateTime = new DateTime(2023, 4, 15, 23, 19, 2, 291, DateTimeKind.Unspecified).AddTicks(4628),
                            Evaluation = 6,
                            FurnitureId = 19,
                            UserId = 1
                        },
                        new
                        {
                            Id = 47,
                            Comment = "Amet harum sunt ducimus sunt. Eaque cum ut sequi. Voluptatem id aut enim deleniti voluptatem quia. Voluptatum id consequatur quis sed perferendis maiores optio. Qui magnam in beatae enim placeat exercitationem. Fuga doloribus quis at fugit ut.",
                            DateTime = new DateTime(2023, 3, 20, 1, 19, 50, 285, DateTimeKind.Unspecified).AddTicks(2245),
                            Evaluation = 11,
                            FurnitureId = 44,
                            UserId = 2
                        },
                        new
                        {
                            Id = 48,
                            Comment = "Quos aut cumque velit cum. Nihil dolor nisi omnis et aut. Dolores sunt nostrum culpa excepturi quae. Soluta et at ad facere pariatur commodi laboriosam aperiam consectetur. Ratione nostrum autem ab in unde autem ea repellendus ipsa.",
                            DateTime = new DateTime(2023, 3, 18, 10, 59, 56, 988, DateTimeKind.Unspecified).AddTicks(8231),
                            Evaluation = 2,
                            FurnitureId = 28,
                            UserId = 1
                        },
                        new
                        {
                            Id = 49,
                            Comment = "Et dolor soluta sint eaque qui. Rerum similique sequi molestiae ducimus eum consequuntur consequatur. Voluptatem error quis consequatur. Dignissimos excepturi maxime.",
                            DateTime = new DateTime(2023, 3, 20, 10, 14, 40, 224, DateTimeKind.Unspecified).AddTicks(8411),
                            Evaluation = 3,
                            FurnitureId = 48,
                            UserId = 1
                        },
                        new
                        {
                            Id = 50,
                            Comment = "Repellendus quisquam atque praesentium maxime nesciunt aliquid tempore rerum quia. Minus deleniti nihil quia non sunt distinctio. Ut saepe quas ut praesentium ullam ipsum nam. Enim non natus voluptas beatae eligendi quis nihil sapiente quis. Quia autem deleniti dolorum sapiente modi.",
                            DateTime = new DateTime(2023, 4, 15, 21, 55, 5, 212, DateTimeKind.Unspecified).AddTicks(2841),
                            Evaluation = 4,
                            FurnitureId = 32,
                            UserId = 1
                        },
                        new
                        {
                            Id = 51,
                            Comment = "Animi ut deserunt voluptatibus minima blanditiis accusantium. Sunt dolores velit ea. Voluptas illum et. Ab esse delectus sed minima totam dolor esse rerum.",
                            DateTime = new DateTime(2023, 3, 24, 7, 2, 47, 815, DateTimeKind.Unspecified).AddTicks(608),
                            Evaluation = 4,
                            FurnitureId = 11,
                            UserId = 3
                        },
                        new
                        {
                            Id = 52,
                            Comment = "Aperiam reprehenderit a et corrupti. Sunt magnam recusandae non consequatur quo vel sed. Velit ea nihil dolor ipsa quia enim. Quia quibusdam velit similique reprehenderit. Temporibus eius commodi molestiae.",
                            DateTime = new DateTime(2023, 3, 27, 1, 18, 34, 29, DateTimeKind.Unspecified).AddTicks(4723),
                            Evaluation = 2,
                            FurnitureId = 41,
                            UserId = 2
                        },
                        new
                        {
                            Id = 53,
                            Comment = "Architecto a neque doloremque. Totam possimus quibusdam exercitationem quis odit eum ut doloremque provident. Est inventore harum. Beatae ratione cumque aut ratione asperiores dignissimos repellendus.",
                            DateTime = new DateTime(2023, 4, 10, 15, 59, 35, 140, DateTimeKind.Unspecified).AddTicks(5224),
                            Evaluation = 4,
                            FurnitureId = 20,
                            UserId = 3
                        },
                        new
                        {
                            Id = 54,
                            Comment = "Odit vitae ipsa minima nisi at ipsa. Enim odit quae sapiente voluptatibus suscipit qui. Animi similique quia dolorum vitae molestiae quaerat veritatis rerum repellat.",
                            DateTime = new DateTime(2023, 4, 16, 1, 1, 4, 370, DateTimeKind.Unspecified).AddTicks(9930),
                            Evaluation = 1,
                            FurnitureId = 25,
                            UserId = 2
                        },
                        new
                        {
                            Id = 55,
                            Comment = "Maxime eligendi et ducimus et ducimus porro dolor. Laudantium officiis deserunt inventore sit perferendis aut reprehenderit. Velit ea numquam laudantium praesentium. Qui reiciendis reprehenderit nisi.",
                            DateTime = new DateTime(2023, 3, 19, 6, 55, 20, 683, DateTimeKind.Unspecified).AddTicks(662),
                            Evaluation = 10,
                            FurnitureId = 39,
                            UserId = 1
                        },
                        new
                        {
                            Id = 56,
                            Comment = "Numquam nostrum esse rerum et. At qui sapiente dolorum. Nam consequatur cumque. Repudiandae in eius corporis voluptates et minima incidunt quod fuga. Inventore quis hic. Commodi aut quibusdam qui ut est eligendi.",
                            DateTime = new DateTime(2023, 3, 28, 11, 52, 43, 785, DateTimeKind.Unspecified).AddTicks(5684),
                            Evaluation = 5,
                            FurnitureId = 28,
                            UserId = 1
                        },
                        new
                        {
                            Id = 57,
                            Comment = "Voluptas magni sequi ut est ea sint. Aut rem rerum dolorem recusandae inventore. Voluptatem quo explicabo atque dignissimos vel quaerat hic. Minima minus quaerat eius consequuntur pariatur aliquam commodi soluta. Reprehenderit est totam fugit consequatur aut aperiam dicta atque. Repudiandae ut aperiam nam voluptatem magni provident tenetur.",
                            DateTime = new DateTime(2023, 3, 28, 15, 48, 43, 517, DateTimeKind.Unspecified).AddTicks(2209),
                            Evaluation = 1,
                            FurnitureId = 30,
                            UserId = 1
                        },
                        new
                        {
                            Id = 58,
                            Comment = "Eligendi a aspernatur optio quis. Eius cupiditate ratione. Libero veritatis pariatur quisquam.",
                            DateTime = new DateTime(2023, 3, 31, 15, 23, 14, 142, DateTimeKind.Unspecified).AddTicks(1722),
                            Evaluation = 8,
                            FurnitureId = 15,
                            UserId = 2
                        },
                        new
                        {
                            Id = 59,
                            Comment = "Tenetur autem optio mollitia velit. Ipsam corporis exercitationem corporis expedita consequatur molestiae dolor quam velit. Suscipit porro qui velit reprehenderit possimus debitis repellat a minima. Tempora deserunt delectus eum consequatur eos suscipit voluptatem quaerat. Dolores quis porro sint tempora voluptas et. Harum libero ullam enim natus architecto culpa quia et.",
                            DateTime = new DateTime(2023, 4, 5, 4, 27, 26, 506, DateTimeKind.Unspecified).AddTicks(2514),
                            Evaluation = 7,
                            FurnitureId = 31,
                            UserId = 3
                        },
                        new
                        {
                            Id = 60,
                            Comment = "Quas architecto nihil laboriosam dolorem alias similique voluptas. Sequi voluptate voluptas. Id dolores dolorem repudiandae autem.",
                            DateTime = new DateTime(2023, 3, 27, 0, 34, 44, 848, DateTimeKind.Unspecified).AddTicks(3587),
                            Evaluation = 2,
                            FurnitureId = 26,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("Furniking.DAL.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b616c486-2b7b-4441-8dbd-0096b713a25b",
                            Email = "user@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "USER@GMAIL.COM",
                            NormalizedUserName = "USER@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEBfR7TYeWK3iPouKuPHdmpubv74fbRO9/SQDHpibpovHym8bWDXMhpfnP2OzyZG6XQ==",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "user@gmail.com"
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f77b1390-1010-4d2f-95cd-63ae918eaff0",
                            Email = "moderator@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "MODERATOR@GMAIL.COM",
                            NormalizedUserName = "MODERATOR@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEA3QY8+YreyiJ/ZbgX1cT7IsIsWLI7ZJliD/+LASffMnWGBdB7CYTF0/tv+wbQacXQ==",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "moderator@gmail.com"
                        },
                        new
                        {
                            Id = 3,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "6bceb58e-71e1-407f-9488-f9442de38ba9",
                            Email = "admin@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@GMAIL.COM",
                            NormalizedUserName = "ADMIN@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEEwet+opf8YtQYfS/kdFjmRAIaRwapGqdKvxY0OqUVRrXj6qaMUfzr9tNIUtO7wYOA==",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "admin@gmail.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "User",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Moderator",
                            NormalizedName = "MODERATOR"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 3,
                            RoleId = 3
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Furniking.DAL.Entities.Furniture", b =>
                {
                    b.HasOne("Furniking.DAL.Entities.Category", "Category")
                        .WithMany("Furnitures")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Furniking.DAL.Entities.Image", b =>
                {
                    b.HasOne("Furniking.DAL.Entities.Furniture", null)
                        .WithMany("Images")
                        .HasForeignKey("FurnitureId");
                });

            modelBuilder.Entity("Furniking.DAL.Entities.Order", b =>
                {
                    b.HasOne("Furniking.DAL.Entities.Furniture", "Furniture")
                        .WithMany()
                        .HasForeignKey("FurnitureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Furniking.DAL.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Furniture");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Furniking.DAL.Entities.Review", b =>
                {
                    b.HasOne("Furniking.DAL.Entities.Furniture", "Furniture")
                        .WithMany("Reviews")
                        .HasForeignKey("FurnitureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Furniking.DAL.Entities.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Furniture");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Furniking.DAL.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Furniking.DAL.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Furniking.DAL.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Furniking.DAL.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Furniking.DAL.Entities.Category", b =>
                {
                    b.Navigation("Furnitures");
                });

            modelBuilder.Entity("Furniking.DAL.Entities.Furniture", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Furniking.DAL.Entities.User", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
