// <auto-generated />
using System;
using Furniking.DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Furniking.DAL.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230414143635_AddedFakeDatas")]
    partial class AddedFakeDatas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Furniking.DAL.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Jewelery"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Health, Music & Games"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Garden"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Industrial & Shoes"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Books, Movies & Music"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Electronics, Electronics & Beauty"
                        });
                });

            modelBuilder.Entity("Furniking.DAL.Entities.Furniture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Furnitures");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 3,
                            Description = "Et quia illo ipsum necessitatibus. Dicta maiores nemo est dolorem quo. Quam fugiat assumenda dolor officia voluptas est ut. Cumque est fugit incidunt. Voluptatem in laboriosam modi labore voluptatem quia velit cum. Minus dicta fuga neque voluptatibus.",
                            Name = "Unbranded Metal Bacon",
                            Price = 398.04292209804220m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 3,
                            Description = "Odit quaerat rerum adipisci deleniti sint aut iure. Eos ullam vel inventore nostrum inventore ratione. Error maiores possimus dolor assumenda. Consequatur officia vel quae velit. Ut rerum dolor eveniet rem expedita minima sapiente quos et. Odit omnis sapiente cumque est.",
                            Name = "Ergonomic Fresh Computer",
                            Price = 307.175615296282360m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 6,
                            Description = "Et ut nihil sequi soluta et. Occaecati doloremque commodi rem. Quis aperiam iure qui labore sint placeat. Aut harum asperiores id voluptates rerum accusantium qui neque. Nobis eum iure quisquam et. Nihil iure quo deserunt amet veritatis aspernatur quos.",
                            Name = "Tasty Plastic Salad",
                            Price = 517.250014988352130m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 3,
                            Description = "Fugiat rerum nostrum nam quod at similique dolores. Quibusdam et aperiam in molestiae. Inventore quaerat sapiente. Enim temporibus id illo sit natus esse inventore et. Autem expedita soluta rem iusto aspernatur numquam.",
                            Name = "Tasty Wooden Shirt",
                            Price = 637.135781339755270m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Description = "Quia similique commodi. Excepturi quam doloremque dolorum consequatur et consequatur velit dolore. Asperiores recusandae animi expedita aut nulla nulla in et. Incidunt et aut tempora optio vel maiores ut ut.",
                            Name = "Sleek Frozen Chair",
                            Price = 260.872971585523210m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Description = "Aut perferendis amet similique dolores quia reiciendis quam soluta. Eos aut laudantium repudiandae sit commodi sint ullam aperiam voluptatem. Quisquam ratione porro maiores sequi culpa voluptatem libero illo qui. Veniam similique vero expedita non sint odio iure. Voluptatibus recusandae et tempora optio qui eius consectetur id. Culpa sit error.",
                            Name = "Ergonomic Steel Computer",
                            Price = 796.9002516805870m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            Description = "Iste eligendi dolorum. Ea et vel aut voluptatem iure molestias aspernatur dignissimos explicabo. Earum laborum laudantium quo eius ex sed voluptas corporis. Dolorum expedita quidem magni et nihil eos explicabo corrupti amet.",
                            Name = "Licensed Metal Pizza",
                            Price = 127.361896266282580m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 4,
                            Description = "Reprehenderit numquam quod minus sapiente officia libero. Blanditiis repellendus iure in possimus dolor omnis et. Molestiae nihil dolorem quia id consequuntur. Enim id dolore nihil fuga. Quia doloremque et. Ut cupiditate occaecati ullam et voluptatem.",
                            Name = "Rustic Wooden Ball",
                            Price = 840.974327370839080m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 5,
                            Description = "Aut et tempora error aut soluta harum. Alias doloribus quia aut laborum expedita quas nisi. Voluptas ex illo quae. Aperiam consectetur aperiam suscipit iste et illum dolorum reiciendis. Illum soluta dolore nesciunt voluptatem sint.",
                            Name = "Gorgeous Concrete Chips",
                            Price = 620.323214950726750m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            Description = "Ratione reprehenderit molestiae. Perferendis saepe culpa. Eum ut enim et quisquam quibusdam sapiente. Blanditiis voluptatibus esse beatae.",
                            Name = "Rustic Plastic Soap",
                            Price = 243.834638740993180m
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 2,
                            Description = "Occaecati ipsum quis rerum qui molestiae accusantium porro. Quo assumenda aut molestias quia consequatur tempore. Sed enim commodi quibusdam et temporibus distinctio.",
                            Name = "Tasty Soft Sausages",
                            Price = 579.135878603723530m
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 3,
                            Description = "Consequatur ut ea quidem doloremque. Hic nihil voluptatibus. Laborum eos maxime nihil.",
                            Name = "Rustic Wooden Cheese",
                            Price = 778.367579758063120m
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 4,
                            Description = "Facere quis velit nostrum sequi dolores est autem molestiae incidunt. Magni cupiditate incidunt eius harum eum facilis laboriosam ullam temporibus. Qui porro debitis eaque qui expedita quibusdam.",
                            Name = "Rustic Wooden Chair",
                            Price = 524.891670815215540m
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 3,
                            Description = "Rerum quo error. Nam sed quod fugiat distinctio cumque qui in id. Ratione quam itaque omnis. Et omnis aliquid aut repellendus voluptatibus.",
                            Name = "Sleek Wooden Pants",
                            Price = 180.208344691938520m
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 1,
                            Description = "Adipisci omnis eum et quo. Eaque magni rerum atque non aut iusto dolor. Est occaecati at aliquid est laboriosam odit aut vero ut.",
                            Name = "Sleek Rubber Chips",
                            Price = 644.138110148473810m
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 6,
                            Description = "Nemo aut inventore. Facilis et quam cum eum id. Qui praesentium aperiam sed velit sint nostrum fuga nobis exercitationem. Dolores iusto accusamus et ut pariatur repudiandae.",
                            Name = "Gorgeous Cotton Sausages",
                            Price = 234.525501283963330m
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 6,
                            Description = "Reprehenderit quidem quia libero voluptas magnam. Doloremque magnam at atque. Aspernatur accusantium illo sit et. Ea nobis eveniet illum fuga rerum laboriosam non. Eum est maiores amet sit. Vel dolorum saepe possimus soluta possimus eum dolor unde pariatur.",
                            Name = "Refined Wooden Soap",
                            Price = 210.76271353489780m
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 5,
                            Description = "Et necessitatibus eligendi dolorem accusantium quo id modi. Velit magnam iure est qui. Laborum excepturi in sed quisquam et. Aliquam sunt tempore non maiores optio sint dolores error.",
                            Name = "Gorgeous Metal Ball",
                            Price = 681.238745614578790m
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 2,
                            Description = "Optio ea et omnis et sapiente velit ducimus dolorum. Amet ratione eveniet consequuntur. Itaque ducimus dolor eaque quia.",
                            Name = "Ergonomic Granite Chicken",
                            Price = 187.584922465774120m
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 2,
                            Description = "Quia omnis et adipisci totam aut quaerat. Culpa quidem nobis quibusdam deserunt assumenda. Nisi eaque et qui dolores magni. Doloribus aut qui aut dolor rerum rerum perspiciatis odio. Voluptas odio repellendus accusantium quis non. Est temporibus dolore veniam est rerum eaque tenetur.",
                            Name = "Practical Soft Chicken",
                            Price = 54.6455908760667850m
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 1,
                            Description = "Accusamus odio quod facere expedita modi sapiente dolorum est nihil. Sit corporis soluta praesentium omnis sit voluptatem eum. Mollitia nostrum incidunt facilis quis voluptatum.",
                            Name = "Generic Metal Computer",
                            Price = 676.036728291159280m
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 3,
                            Description = "Minima perspiciatis adipisci. Ipsam hic blanditiis aliquam voluptatibus eos at incidunt iste. Quis quia at et est et accusamus nulla.",
                            Name = "Small Concrete Shoes",
                            Price = 446.436750984017410m
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 1,
                            Description = "Incidunt harum earum. Natus qui nulla maiores expedita nostrum eum nemo qui sit. Nesciunt pariatur veritatis. Enim officiis qui ut illum odit illum similique ut.",
                            Name = "Fantastic Plastic Keyboard",
                            Price = 231.316975036309240m
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 6,
                            Description = "Qui consequuntur est eos dolores aliquid iste est natus qui. Quibusdam ullam eos sit laudantium quisquam nesciunt qui deleniti. Qui quo maiores sed rerum eveniet repudiandae.",
                            Name = "Small Granite Shirt",
                            Price = 919.772637896927530m
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 4,
                            Description = "Similique maxime doloremque. Aut molestias perspiciatis expedita officia. Quod dolor soluta cupiditate est aliquam. Molestias earum dolorem nam sequi. Voluptas et vel quis laborum neque voluptatem reprehenderit. Aut inventore repellendus minima natus facilis ut aliquid.",
                            Name = "Rustic Metal Table",
                            Price = 742.966794131703670m
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 6,
                            Description = "Quas fugit consequatur natus. Magni itaque enim velit in architecto nesciunt natus. Eum et nemo rem aut. Cumque temporibus sed aut ea minus. Totam ipsam occaecati explicabo. Tempora praesentium eveniet maxime.",
                            Name = "Fantastic Rubber Cheese",
                            Price = 271.653111163188910m
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 6,
                            Description = "In sint deleniti minima quis nulla veritatis explicabo sint perferendis. Tempora et asperiores iure doloremque vitae suscipit consequuntur commodi voluptatem. Quia voluptatem et magni.",
                            Name = "Licensed Wooden Chair",
                            Price = 367.144996013049970m
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 5,
                            Description = "Expedita eaque et asperiores facilis aut. Voluptas a similique aperiam sapiente debitis et quam. Placeat voluptatem exercitationem vero inventore ipsam quo suscipit. Consequatur impedit optio molestias quis totam ex vel laboriosam officia.",
                            Name = "Generic Plastic Gloves",
                            Price = 93.6980056792877140m
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 1,
                            Description = "Ab hic temporibus quia qui perspiciatis voluptas cupiditate. Ipsam architecto assumenda magni. Velit libero aliquid aut officiis corrupti. Distinctio labore est asperiores dolor. Quae iste nihil deserunt sed sit ut ratione. Dolorum eum et sint omnis necessitatibus quas exercitationem ullam.",
                            Name = "Rustic Wooden Shoes",
                            Price = 402.065960352464530m
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 2,
                            Description = "Id fugiat quisquam impedit nesciunt doloribus ab deleniti id ea. Fugit quia sit deserunt voluptatibus. Id veritatis quis. Aut architecto saepe et magnam dicta.",
                            Name = "Fantastic Wooden Mouse",
                            Price = 524.820430308464830m
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 3,
                            Description = "Eligendi suscipit aut deleniti ut doloremque quaerat nihil et. Soluta quisquam architecto et laudantium voluptatum. Asperiores sunt id sint voluptate harum. Sunt dolores beatae non quas.",
                            Name = "Practical Steel Computer",
                            Price = 964.416462915327940m
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 5,
                            Description = "Qui reprehenderit quidem velit natus voluptatem aliquid dicta soluta nam. Dolore ratione eius qui commodi sit et rerum eligendi ut. Ab earum officiis est illo et et nemo. Veritatis minima harum ducimus nihil suscipit reprehenderit nesciunt. Et et atque ratione fugiat est aut vel. Atque magnam minima est.",
                            Name = "Handmade Wooden Gloves",
                            Price = 390.985238019581470m
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 5,
                            Description = "Eaque ullam repellat quia sint non dolor vitae. Error dolores occaecati inventore quia voluptatum. Ut hic quos blanditiis aut nihil et. Voluptatem vitae dolore odit soluta sint laborum fugiat sunt.",
                            Name = "Handcrafted Soft Table",
                            Price = 345.005750527037920m
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 2,
                            Description = "Aut odit nobis ea. Quasi molestiae ad molestias excepturi sunt quos iste temporibus tempora. Debitis ipsam dolorum et sit. Sit eos cumque rerum blanditiis.",
                            Name = "Refined Steel Towels",
                            Price = 222.017630556613420m
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 2,
                            Description = "Ut neque sed odio tenetur mollitia voluptatem enim. Doloribus ut deleniti pariatur. Assumenda quod quasi consequatur molestias. Dolorum ab autem illum qui. Ut animi suscipit ratione magni facilis eveniet quam et. Debitis voluptate nostrum sint.",
                            Name = "Licensed Wooden Keyboard",
                            Price = 819.985143642371290m
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 3,
                            Description = "Odit beatae esse perferendis quo veniam sunt reprehenderit. Porro autem beatae autem saepe est qui voluptas repellat. Incidunt ea rem qui blanditiis et est. Expedita sed sit.",
                            Name = "Generic Cotton Hat",
                            Price = 578.824015302704260m
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 3,
                            Description = "Eos corrupti doloribus ea et. Laudantium aut et iste optio voluptatem autem adipisci qui. Enim non fuga error commodi. At laudantium sed nostrum. Necessitatibus odio voluptas ea magni sed facere sunt totam.",
                            Name = "Handcrafted Concrete Chips",
                            Price = 418.526213611483990m
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 5,
                            Description = "Consectetur porro est unde magnam commodi nemo natus sapiente. Saepe sint error fuga similique autem eos similique. Possimus vero vitae culpa vero sequi et sunt quas. Ratione omnis pariatur.",
                            Name = "Refined Fresh Salad",
                            Price = 759.752529631877530m
                        },
                        new
                        {
                            Id = 39,
                            CategoryId = 1,
                            Description = "Aperiam debitis beatae aliquid occaecati. Excepturi est neque a possimus. Eveniet quos enim ullam non praesentium et vel. Voluptatum sint est aut non ab. Eos id et. Exercitationem ducimus quam est fuga aut aut est consequatur sunt.",
                            Name = "Unbranded Soft Bike",
                            Price = 547.654936610814220m
                        },
                        new
                        {
                            Id = 40,
                            CategoryId = 2,
                            Description = "Quo et sunt distinctio. Sit veritatis voluptatem omnis et. Quo ut culpa sint enim.",
                            Name = "Generic Fresh Bike",
                            Price = 949.659879454136830m
                        },
                        new
                        {
                            Id = 41,
                            CategoryId = 4,
                            Description = "Voluptatibus modi dolorem quos. Impedit sit voluptate voluptas. Non minus qui quisquam facilis accusantium voluptas quia molestiae vero. Quo optio quasi voluptas. Quam inventore pariatur beatae dignissimos recusandae nisi qui quia earum. In quasi doloribus quia quia maxime.",
                            Name = "Unbranded Steel Soap",
                            Price = 488.904242819953060m
                        },
                        new
                        {
                            Id = 42,
                            CategoryId = 6,
                            Description = "Praesentium doloremque consequatur corporis. Ex qui sint illo vel. Omnis consequatur quia qui laudantium accusamus illo. Dolorem accusamus recusandae suscipit rerum veniam sequi. Illum sapiente non magni amet consectetur. Quos quia esse.",
                            Name = "Handmade Granite Shoes",
                            Price = 234.684924826882960m
                        },
                        new
                        {
                            Id = 43,
                            CategoryId = 4,
                            Description = "Quae soluta porro esse atque quaerat eius qui qui. Repellat magnam a ipsa eos provident cumque quidem. Fuga recusandae esse quibusdam fugit quis.",
                            Name = "Unbranded Soft Shirt",
                            Price = 128.6882517376270m
                        },
                        new
                        {
                            Id = 44,
                            CategoryId = 4,
                            Description = "Aut maxime at ipsam voluptatibus similique quidem enim maxime omnis. Dolorem et incidunt et esse ea eos fuga. Totam odio quasi et omnis eum. Labore provident deserunt ut necessitatibus ipsa pariatur quasi eum cumque. Nam natus enim hic in sed aut debitis labore aut.",
                            Name = "Unbranded Steel Fish",
                            Price = 420.505943914605880m
                        },
                        new
                        {
                            Id = 45,
                            CategoryId = 2,
                            Description = "Odit incidunt illo at. Magnam sunt et culpa odio soluta. Eligendi rerum sapiente aspernatur qui.",
                            Name = "Licensed Soft Shoes",
                            Price = 171.143135877480130m
                        },
                        new
                        {
                            Id = 46,
                            CategoryId = 4,
                            Description = "Quos fugiat pariatur ipsa dolorem aut. Aut delectus et adipisci dolores. Pariatur temporibus est quia modi mollitia consectetur temporibus commodi qui.",
                            Name = "Tasty Fresh Bacon",
                            Price = 166.926708490706110m
                        },
                        new
                        {
                            Id = 47,
                            CategoryId = 6,
                            Description = "Voluptatum quo sed veniam omnis est at aut. Reiciendis veniam natus omnis qui. Placeat deleniti voluptatum qui eveniet magnam quia. Aut rerum voluptatum. Consequatur deserunt consequatur. Excepturi quia omnis accusantium ab quia dolorum quo asperiores.",
                            Name = "Practical Plastic Keyboard",
                            Price = 161.212298619430180m
                        },
                        new
                        {
                            Id = 48,
                            CategoryId = 5,
                            Description = "Neque nostrum non ut repellat suscipit. Voluptas fugiat eum. Maxime ut ad autem. Eos quaerat quas quidem qui corporis nam. Soluta debitis eius eos qui unde atque.",
                            Name = "Refined Frozen Pants",
                            Price = 758.877896589267610m
                        },
                        new
                        {
                            Id = 49,
                            CategoryId = 4,
                            Description = "Deleniti voluptatem laboriosam sunt qui rerum quis. Quod qui illo. Distinctio modi quidem asperiores atque aperiam nihil. Ut accusamus repellendus ut tempora et quis. Illo sunt sit repellat facilis dolores.",
                            Name = "Sleek Steel Towels",
                            Price = 832.596230431278820m
                        },
                        new
                        {
                            Id = 50,
                            CategoryId = 5,
                            Description = "Doloremque facere ut perspiciatis aliquam nihil blanditiis sit assumenda. Beatae eligendi accusamus. Corrupti officiis reiciendis voluptatum ipsa delectus eos. Doloribus velit natus autem rem rerum. Blanditiis dolores tenetur totam et quisquam ratione sed ea excepturi.",
                            Name = "Tasty Soft Chair",
                            Price = 156.236508768952360m
                        });
                });

            modelBuilder.Entity("Furniking.DAL.Entities.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FurnitureId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FurnitureId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("Furniking.DAL.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int>("FurnitureId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FurnitureId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Furniking.DAL.Entities.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Evaluation")
                        .HasColumnType("int");

                    b.Property<int>("FurnitureId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FurnitureId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comment = "At omnis voluptates omnis. Nobis aliquid ipsa et. Consequatur dignissimos omnis pariatur unde. Ipsa recusandae architecto temporibus ut voluptatem voluptatem ipsum blanditiis. Quidem sed velit id omnis voluptas.",
                            DateTime = new DateTime(2023, 4, 14, 14, 36, 35, 563, DateTimeKind.Utc).AddTicks(5963),
                            Evaluation = 1,
                            FurnitureId = 15,
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            Comment = "Quas culpa assumenda exercitationem. Tempore eum aut. Aut dolorem esse voluptas. Voluptate numquam impedit vel dicta voluptatem. Adipisci perferendis modi eius totam rerum aperiam qui. Et id corporis aut provident corrupti et.",
                            DateTime = new DateTime(2023, 4, 14, 14, 36, 35, 563, DateTimeKind.Utc).AddTicks(7613),
                            Evaluation = 9,
                            FurnitureId = 28,
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            Comment = "Qui molestias cum consectetur nihil. Ut molestiae nobis dolores. Aut nostrum qui voluptatem omnis. Iure nam omnis sapiente nemo eligendi. Sit qui veniam non. Unde accusantium aut earum ipsum cupiditate quos.",
                            DateTime = new DateTime(2023, 4, 14, 14, 36, 35, 563, DateTimeKind.Utc).AddTicks(7800),
                            Evaluation = 8,
                            FurnitureId = 44,
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            Comment = "Suscipit et porro. Laudantium est magnam illum tempora veritatis cumque blanditiis. Delectus sit ea porro veniam. Reiciendis occaecati exercitationem molestiae sed quia voluptatem voluptatem. Nostrum ipsa enim et fuga. Consequuntur dolores et hic sed qui.",
                            DateTime = new DateTime(2023, 4, 14, 14, 36, 35, 563, DateTimeKind.Utc).AddTicks(7954),
                            Evaluation = 9,
                            FurnitureId = 9,
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            Comment = "Vel est perferendis totam dolor consectetur. Asperiores vero consequuntur quis. Sint rerum magni sunt repellat. Expedita ea nesciunt sint nesciunt aut. Eos molestias mollitia vel suscipit ullam laudantium eligendi.",
                            DateTime = new DateTime(2023, 4, 14, 14, 36, 35, 563, DateTimeKind.Utc).AddTicks(8098),
                            Evaluation = 6,
                            FurnitureId = 39,
                            UserId = 1
                        },
                        new
                        {
                            Id = 6,
                            Comment = "Dolorem saepe dolorem. Saepe eum impedit at. Et quo delectus similique voluptas impedit.",
                            DateTime = new DateTime(2023, 4, 14, 14, 36, 35, 563, DateTimeKind.Utc).AddTicks(8216),
                            Evaluation = 11,
                            FurnitureId = 42,
                            UserId = 3
                        },
                        new
                        {
                            Id = 7,
                            Comment = "Optio odio ipsam iusto iusto eos recusandae sit soluta cum. Pariatur qui ea ad debitis repudiandae porro. Magnam quam nihil nihil ipsum.",
                            DateTime = new DateTime(2023, 4, 14, 14, 36, 35, 563, DateTimeKind.Utc).AddTicks(8308),
                            Evaluation = 7,
                            FurnitureId = 13,
                            UserId = 1
                        },
                        new
                        {
                            Id = 8,
                            Comment = "Exercitationem est corrupti autem illo voluptatum non deleniti illo. Quas architecto error illo labore magnam et ipsa. Vitae et deserunt exercitationem aut qui dolores aut. Velit animi vel. In quo repudiandae nobis aut. Ut illum qui nostrum error sit possimus nulla.",
                            DateTime = new DateTime(2023, 4, 14, 14, 36, 35, 563, DateTimeKind.Utc).AddTicks(8483),
                            Evaluation = 1,
                            FurnitureId = 49,
                            UserId = 3
                        },
                        new
                        {
                            Id = 9,
                            Comment = "Voluptatum et modi sit est. Vel enim sed alias accusantium. Aut ut eum reiciendis sit eum provident. Incidunt eveniet aut sit. Error harum aliquam.",
                            DateTime = new DateTime(2023, 4, 14, 14, 36, 35, 563, DateTimeKind.Utc).AddTicks(8591),
                            Evaluation = 2,
                            FurnitureId = 9,
                            UserId = 1
                        },
                        new
                        {
                            Id = 10,
                            Comment = "In aut blanditiis distinctio. Excepturi facere et tempore enim. Incidunt unde rerum debitis aut vero beatae vero.",
                            DateTime = new DateTime(2023, 4, 14, 14, 36, 35, 563, DateTimeKind.Utc).AddTicks(8670),
                            Evaluation = 9,
                            FurnitureId = 44,
                            UserId = 2
                        },
                        new
                        {
                            Id = 11,
                            Comment = "Et voluptatum quaerat. Ratione iure minima neque occaecati. Sit quisquam quia. Et doloribus quos autem rerum.",
                            DateTime = new DateTime(2023, 4, 14, 14, 36, 35, 563, DateTimeKind.Utc).AddTicks(8753),
                            Evaluation = 8,
                            FurnitureId = 42,
                            UserId = 1
                        },
                        new
                        {
                            Id = 12,
                            Comment = "Minus earum nihil. Est mollitia animi consequatur nostrum. Cupiditate est quas quisquam molestiae et sequi delectus. Illo facere ipsum dolores ex perspiciatis consequatur. Sapiente quaerat asperiores nobis.",
                            DateTime = new DateTime(2023, 4, 14, 14, 36, 35, 563, DateTimeKind.Utc).AddTicks(8863),
                            Evaluation = 2,
                            FurnitureId = 27,
                            UserId = 1
                        },
                        new
                        {
                            Id = 13,
                            Comment = "At perspiciatis pariatur voluptatem odio voluptas debitis quia et tempora. Consequatur voluptate enim. A provident illum accusamus nam est nam corrupti. Quidem explicabo itaque sit qui voluptatem aut. Repellat in ipsa omnis illo consequatur ipsum deserunt magni. Porro eligendi amet eligendi ut cupiditate.",
                            DateTime = new DateTime(2023, 4, 14, 14, 36, 35, 563, DateTimeKind.Utc).AddTicks(9028),
                            Evaluation = 10,
                            FurnitureId = 47,
                            UserId = 1
                        },
                        new
                        {
                            Id = 14,
                            Comment = "Quia amet sed culpa. Quos voluptatibus non quia. Odit qui aperiam sint consectetur iste consectetur eius sapiente soluta. Qui et eius possimus rem omnis natus dolor. Cumque quo corrupti voluptatem fugit ipsam voluptatem nulla omnis. Fugiat fuga et quidem repellat adipisci eligendi quo quo.",
                            DateTime = new DateTime(2023, 4, 14, 14, 36, 35, 563, DateTimeKind.Utc).AddTicks(9234),
                            Evaluation = 8,
                            FurnitureId = 38,
                            UserId = 1
                        },
                        new
                        {
                            Id = 15,
                            Comment = "Nihil labore vero qui sint sunt. Repellat ut quidem. Nostrum voluptatum saepe est ad. Ut iste occaecati quo at excepturi non et qui. Modi voluptas tempore quo sunt. Corrupti modi iste aut magnam voluptas sed.",
                            DateTime = new DateTime(2023, 4, 14, 14, 36, 35, 563, DateTimeKind.Utc).AddTicks(9361),
                            Evaluation = 1,
                            FurnitureId = 10,
                            UserId = 2
                        },
                        new
                        {
                            Id = 16,
                            Comment = "Saepe quam nobis excepturi. Ipsam deleniti repudiandae aut quos aut aliquam eaque quidem. Veritatis enim sit quam non corrupti reprehenderit et autem repellendus. Qui libero ex expedita aut eligendi omnis voluptatem nisi odit. Tempora voluptatum perspiciatis iure est expedita animi qui laudantium ea.",
                            DateTime = new DateTime(2023, 4, 14, 14, 36, 35, 563, DateTimeKind.Utc).AddTicks(9512),
                            Evaluation = 7,
                            FurnitureId = 29,
                            UserId = 2
                        },
                        new
                        {
                            Id = 17,
                            Comment = "Doloribus non beatae est error excepturi rerum rerum. Harum nihil eligendi quisquam. Quos dolores fugiat quis unde culpa tempore voluptatum eum. Tempora et non earum mollitia sint expedita. Provident nemo aspernatur.",
                            DateTime = new DateTime(2023, 4, 14, 14, 36, 35, 563, DateTimeKind.Utc).AddTicks(9629),
                            Evaluation = 1,
                            FurnitureId = 44,
                            UserId = 1
                        },
                        new
                        {
                            Id = 18,
                            Comment = "Velit quae iure vero officiis iste enim cum. Minima voluptatem voluptatum dolor eum quia commodi qui possimus. Ducimus vel nisi dolores non et. Et non optio possimus ut. Rerum explicabo facere dolorem nemo at voluptate qui est.",
                            DateTime = new DateTime(2023, 4, 14, 14, 36, 35, 563, DateTimeKind.Utc).AddTicks(9760),
                            Evaluation = 9,
                            FurnitureId = 7,
                            UserId = 1
                        },
                        new
                        {
                            Id = 19,
                            Comment = "Facilis et omnis deleniti rerum ducimus ut. Dolorem optio quaerat voluptatem sunt repellat magni. Voluptatem est cum sit praesentium blanditiis odio perspiciatis.",
                            DateTime = new DateTime(2023, 4, 14, 14, 36, 35, 563, DateTimeKind.Utc).AddTicks(9843),
                            Evaluation = 8,
                            FurnitureId = 23,
                            UserId = 3
                        },
                        new
                        {
                            Id = 20,
                            Comment = "Recusandae et quia enim in sunt laborum. Non voluptates ipsa non recusandae vel officiis sint. Non explicabo distinctio sapiente dolorum sed. Et ut voluptas asperiores mollitia dignissimos perferendis expedita. Fugit voluptatum ut quas. Ducimus nemo ipsam harum.",
                            DateTime = new DateTime(2023, 4, 14, 14, 36, 35, 563, DateTimeKind.Utc).AddTicks(9979),
                            Evaluation = 3,
                            FurnitureId = 33,
                            UserId = 2
                        },
                        new
                        {
                            Id = 21,
                            Comment = "Omnis quia culpa et aliquam est facilis veritatis a et. Veniam est ut et sit aut. Deleniti dicta ut ab. Nihil fuga consequuntur voluptate repellat esse est et est.",
                            DateTime = new DateTime(2023, 4, 14, 14, 36, 35, 564, DateTimeKind.Utc).AddTicks(88),
                            Evaluation = 11,
                            FurnitureId = 43,
                            UserId = 3
                        },
                        new
                        {
                            Id = 22,
                            Comment = "Eos tempore maiores nesciunt qui occaecati sit sunt magnam. Alias rem hic voluptas quibusdam velit hic sunt eos. Reiciendis qui quibusdam quaerat vel officiis et aspernatur minus. Placeat rem totam. In cupiditate consequuntur incidunt dolorum quidem et molestias est repellendus. Et nihil aliquid quis.",
                            DateTime = new DateTime(2023, 4, 14, 14, 36, 35, 564, DateTimeKind.Utc).AddTicks(240),
                            Evaluation = 3,
                            FurnitureId = 4,
                            UserId = 3
                        },
                        new
                        {
                            Id = 23,
                            Comment = "Et cum deserunt. Eos necessitatibus perspiciatis enim et quae est iusto quis. Est provident iusto et illo quaerat.",
                            DateTime = new DateTime(2023, 4, 14, 14, 36, 35, 564, DateTimeKind.Utc).AddTicks(321),
                            Evaluation = 8,
                            FurnitureId = 10,
                            UserId = 1
                        },
                        new
                        {
                            Id = 24,
                            Comment = "Amet eum eum ut. Consequatur et natus culpa suscipit dolor modi sequi temporibus. Mollitia sit quisquam ducimus sed esse error. Et nulla dignissimos. Voluptas ea sunt voluptatibus maxime consequatur sit. Id quis sit.",
                            DateTime = new DateTime(2023, 4, 14, 14, 36, 35, 564, DateTimeKind.Utc).AddTicks(438),
                            Evaluation = 9,
                            FurnitureId = 19,
                            UserId = 2
                        },
                        new
                        {
                            Id = 25,
                            Comment = "Corporis velit ullam aut provident sint. Nisi omnis facere assumenda sed voluptatem aliquid in. Temporibus est consequatur quidem libero perspiciatis. Dolores deserunt minima est quia non labore debitis libero. Et aspernatur quis corporis quia molestiae ut ducimus voluptatem et. Culpa quasi maxime impedit error quod culpa.",
                            DateTime = new DateTime(2023, 4, 14, 14, 36, 35, 564, DateTimeKind.Utc).AddTicks(595),
                            Evaluation = 5,
                            FurnitureId = 35,
                            UserId = 3
                        },
                        new
                        {
                            Id = 26,
                            Comment = "Sed qui quos nihil doloribus. Omnis modi repellendus in non. Sunt explicabo et. Nesciunt beatae debitis laboriosam iusto sed.",
                            DateTime = new DateTime(2023, 4, 14, 14, 36, 35, 564, DateTimeKind.Utc).AddTicks(680),
                            Evaluation = 11,
                            FurnitureId = 47,
                            UserId = 1
                        },
                        new
                        {
                            Id = 27,
                            Comment = "Ducimus at molestiae voluptatibus enim. Vero rerum nisi molestias odit perferendis non totam. Nulla qui quia iste.",
                            DateTime = new DateTime(2023, 4, 14, 14, 36, 35, 564, DateTimeKind.Utc).AddTicks(752),
                            Evaluation = 4,
                            FurnitureId = 8,
                            UserId = 1
                        },
                        new
                        {
                            Id = 28,
                            Comment = "Quisquam voluptates omnis. Eveniet voluptatum nobis officia dolorem. Consequuntur aut sint mollitia nemo.",
                            DateTime = new DateTime(2023, 4, 14, 14, 36, 35, 564, DateTimeKind.Utc).AddTicks(814),
                            Evaluation = 6,
                            FurnitureId = 26,
                            UserId = 3
                        },
                        new
                        {
                            Id = 29,
                            Comment = "Est velit qui qui autem. Et eum est quis est officia. Officia impedit quisquam vel. Qui id rem. Nesciunt qui voluptas animi facilis harum quia dolorem molestiae laboriosam.",
                            DateTime = new DateTime(2023, 4, 14, 14, 36, 35, 564, DateTimeKind.Utc).AddTicks(929),
                            Evaluation = 10,
                            FurnitureId = 23,
                            UserId = 3
                        },
                        new
                        {
                            Id = 30,
                            Comment = "Excepturi commodi aut. Nam nobis impedit sed omnis repellat harum architecto. Rerum fuga consequatur occaecati eligendi dolorum. Voluptates eum dolores aut.",
                            DateTime = new DateTime(2023, 4, 14, 14, 36, 35, 564, DateTimeKind.Utc).AddTicks(1093),
                            Evaluation = 9,
                            FurnitureId = 19,
                            UserId = 2
                        },
                        new
                        {
                            Id = 31,
                            Comment = "Quisquam at maxime delectus enim sit nihil et. Nisi inventore soluta et quia ratione voluptas nemo incidunt. Illo quibusdam eaque quis in quos sunt ut. Non qui voluptas optio et qui vel omnis.",
                            DateTime = new DateTime(2023, 4, 14, 14, 36, 35, 564, DateTimeKind.Utc).AddTicks(1219),
                            Evaluation = 1,
                            FurnitureId = 44,
                            UserId = 3
                        },
                        new
                        {
                            Id = 32,
                            Comment = "Numquam et quidem. Rem quo quod delectus odit voluptatem voluptas iure. Praesentium eum quod suscipit.",
                            DateTime = new DateTime(2023, 4, 14, 14, 36, 35, 564, DateTimeKind.Utc).AddTicks(1289),
                            Evaluation = 3,
                            FurnitureId = 50,
                            UserId = 2
                        },
                        new
                        {
                            Id = 33,
                            Comment = "Dolor numquam doloremque et et quam autem iusto enim. In hic possimus repudiandae qui rem harum. Rerum eos reiciendis.",
                            DateTime = new DateTime(2023, 4, 14, 14, 36, 35, 564, DateTimeKind.Utc).AddTicks(1364),
                            Evaluation = 8,
                            FurnitureId = 29,
                            UserId = 2
                        },
                        new
                        {
                            Id = 34,
                            Comment = "Deleniti expedita vero nulla non fugiat quia cupiditate omnis ut. In laboriosam non quis enim iusto ad. Quibusdam sit magnam non. Eos hic quisquam et quia. Omnis odit voluptas et magnam. Ipsa deserunt neque nihil perferendis aut beatae.",
                            DateTime = new DateTime(2023, 4, 14, 14, 36, 35, 564, DateTimeKind.Utc).AddTicks(1497),
                            Evaluation = 2,
                            FurnitureId = 17,
                            UserId = 3
                        },
                        new
                        {
                            Id = 35,
                            Comment = "Rerum recusandae dolorem. Aut enim cum molestiae molestiae. Maxime rem aut dolor voluptates et necessitatibus nulla porro. Adipisci inventore suscipit ut et hic nostrum. Eveniet voluptatem et.",
                            DateTime = new DateTime(2023, 4, 14, 14, 36, 35, 564, DateTimeKind.Utc).AddTicks(1599),
                            Evaluation = 10,
                            FurnitureId = 8,
                            UserId = 1
                        },
                        new
                        {
                            Id = 36,
                            Comment = "Expedita itaque sint. Aut asperiores explicabo porro error est. Laborum rem cupiditate cumque recusandae sed. Aut repellendus numquam officia repellat fugiat. Ab modi accusamus saepe ullam voluptas occaecati.",
                            DateTime = new DateTime(2023, 4, 14, 14, 36, 35, 564, DateTimeKind.Utc).AddTicks(1707),
                            Evaluation = 4,
                            FurnitureId = 9,
                            UserId = 2
                        },
                        new
                        {
                            Id = 37,
                            Comment = "Sit vel facilis quo est at quaerat suscipit corporis et. Sint itaque consequatur est. Ducimus dolores ea similique consequatur delectus.",
                            DateTime = new DateTime(2023, 4, 14, 14, 36, 35, 564, DateTimeKind.Utc).AddTicks(1782),
                            Evaluation = 7,
                            FurnitureId = 10,
                            UserId = 2
                        },
                        new
                        {
                            Id = 38,
                            Comment = "Voluptas doloremque atque modi molestiae hic eius quas. Quia autem fuga atque accusantium non blanditiis consequatur in. Omnis aut fuga ut blanditiis eligendi ex odit nostrum. Vitae explicabo rem quia. Necessitatibus qui similique quia quia aperiam qui.",
                            DateTime = new DateTime(2023, 4, 14, 14, 36, 35, 564, DateTimeKind.Utc).AddTicks(1910),
                            Evaluation = 8,
                            FurnitureId = 2,
                            UserId = 3
                        },
                        new
                        {
                            Id = 39,
                            Comment = "Consequatur excepturi nam laudantium ut voluptatem consequatur omnis blanditiis. Laudantium officiis facilis necessitatibus quia asperiores dolore. Consequatur inventore dicta assumenda libero voluptatum ipsa dolorum saepe omnis. Quisquam non velit. Est dolores laudantium veniam et id non dignissimos atque.",
                            DateTime = new DateTime(2023, 4, 14, 14, 36, 35, 564, DateTimeKind.Utc).AddTicks(2045),
                            Evaluation = 10,
                            FurnitureId = 47,
                            UserId = 2
                        },
                        new
                        {
                            Id = 40,
                            Comment = "Excepturi omnis animi error blanditiis quod ad non nostrum. Cumque ut rerum impedit dolores est voluptates qui voluptatem. Sequi aspernatur iure eaque tempore cum molestiae. Nihil velit quisquam error aut neque sint veritatis dolore. Aliquam consequatur maiores autem officia culpa. Sed et id dolorem aliquid repellat.",
                            DateTime = new DateTime(2023, 4, 14, 14, 36, 35, 564, DateTimeKind.Utc).AddTicks(2196),
                            Evaluation = 5,
                            FurnitureId = 16,
                            UserId = 1
                        },
                        new
                        {
                            Id = 41,
                            Comment = "Aut iure nesciunt magni exercitationem aperiam repudiandae. Vero et quis ipsa sint. Sunt quasi eius velit. Eaque eum aut ut ut ratione. Nam repellendus porro quia perferendis deleniti sint. Sint occaecati nam.",
                            DateTime = new DateTime(2023, 4, 14, 14, 36, 35, 564, DateTimeKind.Utc).AddTicks(2320),
                            Evaluation = 1,
                            FurnitureId = 45,
                            UserId = 1
                        },
                        new
                        {
                            Id = 42,
                            Comment = "Excepturi consequatur ratione in eum quos voluptate. Tempore incidunt necessitatibus ducimus fugit quaerat quia in quod at. Recusandae vitae aut voluptates sed omnis consequatur omnis error ullam. In perferendis et.",
                            DateTime = new DateTime(2023, 4, 14, 14, 36, 35, 564, DateTimeKind.Utc).AddTicks(2423),
                            Evaluation = 10,
                            FurnitureId = 41,
                            UserId = 2
                        },
                        new
                        {
                            Id = 43,
                            Comment = "Doloribus dolores et dolores. Illum commodi quos accusantium molestiae. Sit nostrum sed officiis. Officiis ducimus exercitationem occaecati ipsa nisi placeat. Quidem et dicta id.",
                            DateTime = new DateTime(2023, 4, 14, 14, 36, 35, 564, DateTimeKind.Utc).AddTicks(2520),
                            Evaluation = 7,
                            FurnitureId = 38,
                            UserId = 1
                        },
                        new
                        {
                            Id = 44,
                            Comment = "Eveniet molestiae consectetur ea quia nemo aliquam repellendus. Vitae in et tenetur nostrum ullam excepturi ea. Velit nam ullam assumenda. A dolorum non magnam repudiandae voluptas vel officia dolor. Autem occaecati quam nobis minima vel dolores quos ea.",
                            DateTime = new DateTime(2023, 4, 14, 14, 36, 35, 564, DateTimeKind.Utc).AddTicks(2643),
                            Evaluation = 5,
                            FurnitureId = 25,
                            UserId = 2
                        },
                        new
                        {
                            Id = 45,
                            Comment = "Eum qui odio ut delectus. Dolorem porro sunt nobis sit magni. Amet aut sit id animi sed est iste pariatur aut. Incidunt ipsa quo omnis sunt rerum quia omnis. Qui molestiae saepe non quisquam dicta odit est.",
                            DateTime = new DateTime(2023, 4, 14, 14, 36, 35, 564, DateTimeKind.Utc).AddTicks(2771),
                            Evaluation = 6,
                            FurnitureId = 13,
                            UserId = 1
                        },
                        new
                        {
                            Id = 46,
                            Comment = "Magnam omnis nisi rerum animi perferendis est est voluptas. Dolorum eos eos at ut nobis tempora neque iste. A magni dignissimos. Quo occaecati et voluptas perspiciatis. Non non ad at aut rerum et qui nostrum. Vitae id suscipit voluptatem.",
                            DateTime = new DateTime(2023, 4, 14, 14, 36, 35, 564, DateTimeKind.Utc).AddTicks(2907),
                            Evaluation = 6,
                            FurnitureId = 49,
                            UserId = 1
                        },
                        new
                        {
                            Id = 47,
                            Comment = "Repellat sit vitae tempore molestiae corporis sit sit enim consequatur. Voluptas vero occaecati et eos error nobis. Totam pariatur ex expedita officiis deserunt quia est eligendi iste. Molestias nostrum voluptatibus doloremque sequi et laudantium natus perferendis quia. Velit non quas sunt est. Ipsam alias aliquid aut.",
                            DateTime = new DateTime(2023, 4, 14, 14, 36, 35, 564, DateTimeKind.Utc).AddTicks(3063),
                            Evaluation = 11,
                            FurnitureId = 41,
                            UserId = 2
                        },
                        new
                        {
                            Id = 48,
                            Comment = "Nihil perspiciatis a facere. Debitis sapiente aliquid quia est eligendi fugiat recusandae voluptatem perspiciatis. Numquam ut sunt asperiores exercitationem ipsam aut enim. Et voluptas laboriosam eligendi provident incidunt vel facilis aut. Inventore velit in nemo quo.",
                            DateTime = new DateTime(2023, 4, 14, 14, 36, 35, 564, DateTimeKind.Utc).AddTicks(3209),
                            Evaluation = 3,
                            FurnitureId = 21,
                            UserId = 3
                        },
                        new
                        {
                            Id = 49,
                            Comment = "Recusandae quo facilis quia porro repellat laborum esse repudiandae iusto. Dolores et nesciunt velit quod. Cum quo eius aut ducimus possimus omnis deserunt. Qui sed aperiam sit exercitationem alias dolor qui. Repellendus fugiat ea iusto suscipit voluptas eos eaque aspernatur sit.",
                            DateTime = new DateTime(2023, 4, 14, 14, 36, 35, 564, DateTimeKind.Utc).AddTicks(3346),
                            Evaluation = 1,
                            FurnitureId = 42,
                            UserId = 3
                        },
                        new
                        {
                            Id = 50,
                            Comment = "Hic soluta veniam porro excepturi iste non. Natus officia qui quos aliquid qui consequatur quisquam voluptas autem. Iusto iure tempore exercitationem non sunt velit. Sit eos dignissimos. Dignissimos quisquam aut id illum consequuntur.",
                            DateTime = new DateTime(2023, 4, 14, 14, 36, 35, 564, DateTimeKind.Utc).AddTicks(3467),
                            Evaluation = 1,
                            FurnitureId = 32,
                            UserId = 1
                        },
                        new
                        {
                            Id = 51,
                            Comment = "Quia non ea unde et ea quam ut explicabo aut. Minus dolor sunt voluptas. Deserunt voluptatem dolor aliquam aspernatur odit eligendi officiis. Iusto similique minima quibusdam.",
                            DateTime = new DateTime(2023, 4, 14, 14, 36, 35, 564, DateTimeKind.Utc).AddTicks(3566),
                            Evaluation = 8,
                            FurnitureId = 33,
                            UserId = 1
                        },
                        new
                        {
                            Id = 52,
                            Comment = "Repellat et a dolores et perferendis ad odit eveniet soluta. Facilis sunt nisi non quam ad. Provident molestiae in reiciendis est incidunt nam atque. Animi dicta quia eligendi illo quaerat vero vel placeat. Beatae porro et cupiditate ratione repudiandae voluptate temporibus. Consequuntur quia ut ut molestias eos.",
                            DateTime = new DateTime(2023, 4, 14, 14, 36, 35, 564, DateTimeKind.Utc).AddTicks(3718),
                            Evaluation = 4,
                            FurnitureId = 2,
                            UserId = 2
                        },
                        new
                        {
                            Id = 53,
                            Comment = "Saepe soluta et accusamus magni culpa velit deserunt deleniti. Et placeat illum. Ea voluptate voluptatem nemo animi a sed autem incidunt. Ipsum consequuntur non.",
                            DateTime = new DateTime(2023, 4, 14, 14, 36, 35, 564, DateTimeKind.Utc).AddTicks(3813),
                            Evaluation = 5,
                            FurnitureId = 44,
                            UserId = 1
                        },
                        new
                        {
                            Id = 54,
                            Comment = "Amet autem quasi a reprehenderit. Nam minus blanditiis. Qui illo est unde quo impedit. Magnam consectetur in sit. Voluptate nemo ducimus ipsum deleniti voluptas deleniti. Autem suscipit et nesciunt enim quibusdam tempore consequatur sunt.",
                            DateTime = new DateTime(2023, 4, 14, 14, 36, 35, 564, DateTimeKind.Utc).AddTicks(3936),
                            Evaluation = 11,
                            FurnitureId = 50,
                            UserId = 3
                        },
                        new
                        {
                            Id = 55,
                            Comment = "Rem ut quas voluptas eius reprehenderit corrupti cumque error. Dolorem repudiandae vel nihil ipsa numquam numquam est cupiditate. Et neque qui repellat corporis nesciunt eligendi neque. Facilis impedit facilis sit provident. Voluptate necessitatibus molestias nihil voluptates quasi omnis id cum.",
                            DateTime = new DateTime(2023, 4, 14, 14, 36, 35, 564, DateTimeKind.Utc).AddTicks(4066),
                            Evaluation = 4,
                            FurnitureId = 45,
                            UserId = 1
                        },
                        new
                        {
                            Id = 56,
                            Comment = "Eos doloribus culpa. Voluptatibus sunt voluptas. Quo mollitia perspiciatis dolorem earum.",
                            DateTime = new DateTime(2023, 4, 14, 14, 36, 35, 564, DateTimeKind.Utc).AddTicks(4128),
                            Evaluation = 10,
                            FurnitureId = 5,
                            UserId = 2
                        },
                        new
                        {
                            Id = 57,
                            Comment = "Quia eaque id magnam quibusdam nisi beatae. Saepe aliquam est beatae sit architecto reprehenderit perferendis recusandae quia. Et non exercitationem ad quia saepe.",
                            DateTime = new DateTime(2023, 4, 14, 14, 36, 35, 564, DateTimeKind.Utc).AddTicks(4212),
                            Evaluation = 3,
                            FurnitureId = 33,
                            UserId = 2
                        },
                        new
                        {
                            Id = 58,
                            Comment = "Occaecati fugit facere exercitationem sed tempora. In eos voluptatem hic rerum quibusdam veniam ullam libero. Et distinctio mollitia est iure nobis. Quos voluptatem omnis illo quisquam mollitia sed quod dolorum rem. Ut id facere iure suscipit fuga. Adipisci pariatur assumenda pariatur libero odio fugiat.",
                            DateTime = new DateTime(2023, 4, 14, 14, 36, 35, 564, DateTimeKind.Utc).AddTicks(4360),
                            Evaluation = 11,
                            FurnitureId = 14,
                            UserId = 1
                        },
                        new
                        {
                            Id = 59,
                            Comment = "Non corporis amet occaecati fuga omnis et vitae. Error enim fugit hic. Cupiditate nobis accusantium dolores. Quidem et consectetur possimus.",
                            DateTime = new DateTime(2023, 4, 14, 14, 36, 35, 564, DateTimeKind.Utc).AddTicks(4447),
                            Evaluation = 5,
                            FurnitureId = 28,
                            UserId = 2
                        },
                        new
                        {
                            Id = 60,
                            Comment = "Dolorem iste magni omnis sapiente eligendi ducimus. Maxime quam deleniti quia quidem. Et dolorem omnis ut.",
                            DateTime = new DateTime(2023, 4, 14, 14, 36, 35, 564, DateTimeKind.Utc).AddTicks(4512),
                            Evaluation = 1,
                            FurnitureId = 9,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("Furniking.DAL.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c7b4b666-38d4-4319-a606-d35bb4b642f7",
                            Email = "user@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "USER@GMAIL.COM",
                            NormalizedUserName = "USER@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEJ9oxPbm0ApqYnR/fumfChP8DaVOaUfiQIi6zH75SqeptfUfC+eSwtQ+EWB7T4Gb4Q==",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "user@gmail.com"
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "6eb2b563-0de1-4d5e-a68b-2261fe921131",
                            Email = "moderator@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "MODERATOR@GMAIL.COM",
                            NormalizedUserName = "MODERATOR@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEFTy10Pb0ueGaAtJYncZkTWzdwwOxABp0kYZdzC/Op7THlWcZSj18c/EDfXqaolqpw==",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "moderator@gmail.com"
                        },
                        new
                        {
                            Id = 3,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3d6aeb4d-2ac7-47b8-b2c2-61b2c3df4a36",
                            Email = "admin@gmail.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@GMAIL.COM",
                            NormalizedUserName = "ADMIN@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEAUieu8dk45LF0ibjiFd4w2C7cP5WPwWGouwg1QaJlDh6RMhjzbiaXPP/0K33Mxn0g==",
                            PhoneNumberConfirmed = false,
                            TwoFactorEnabled = false,
                            UserName = "admin@gmail.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "User",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Moderator",
                            NormalizedName = "MODERATOR"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 3,
                            RoleId = 3
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Furniking.DAL.Entities.Furniture", b =>
                {
                    b.HasOne("Furniking.DAL.Entities.Category", "Category")
                        .WithMany("Furnitures")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Furniking.DAL.Entities.Image", b =>
                {
                    b.HasOne("Furniking.DAL.Entities.Furniture", null)
                        .WithMany("Images")
                        .HasForeignKey("FurnitureId");
                });

            modelBuilder.Entity("Furniking.DAL.Entities.Order", b =>
                {
                    b.HasOne("Furniking.DAL.Entities.Furniture", "Furniture")
                        .WithMany()
                        .HasForeignKey("FurnitureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Furniking.DAL.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Furniture");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Furniking.DAL.Entities.Review", b =>
                {
                    b.HasOne("Furniking.DAL.Entities.Furniture", "Furniture")
                        .WithMany("Reviews")
                        .HasForeignKey("FurnitureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Furniking.DAL.Entities.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Furniture");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Furniking.DAL.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Furniking.DAL.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Furniking.DAL.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Furniking.DAL.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Furniking.DAL.Entities.Category", b =>
                {
                    b.Navigation("Furnitures");
                });

            modelBuilder.Entity("Furniking.DAL.Entities.Furniture", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Furniking.DAL.Entities.User", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
